### ISSUE TITLE
How about "Network Information API".    This has been in Android since version 2.2

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1031]
How about &quot;Network Information API&quot;. 
http://www.w3.org/TR/netinfo-api/

This has been in Android since version 2.2

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+24__
Issue added by __difro__ on __2012-03-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by jakub-g** [comment]
I've been just trying to figure out the support for the feature and it's a bit of a mess

This document says the works on standardization were suspended
https://dvcs.w3.org/hg/dap/raw-file/tip/network-api/Overview.html

But OTOH it can be found here, newer then the previous document:
http://w3c.github.io/netinfo/

MDN says it is enabled since Firefox 12
https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API

but in fact, it seems that (Windows 7 desktop, Firefox 38) by default `dom.netinfo.enabled` is `false`

On Chrome 42 @ Android 4.4.4 I see the following:

```
Object.keys(navigator.connection)

> ["ontypechange", "type"]
```

so a very limited subset of support

**Comment by AshleyWright** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=netinfo
