### ISSUE TITLE
window.onerror -  /  - particularly mobile browser support

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1199]
window.onerror - http://www.w3.org/wiki/DOM/window.onerror / http://www.quirksmode.org/dom/events/error.html - particularly mobile browser support

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+7**
Issue added by **CupawnTae** on **2012-05-23**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Jacse** [comment]
+1

**Comment by mjsmale** [comment]
+1

**Comment by cvrebert** [comment]
https://html.spec.whatwg.org/multipage/webappapis.html#handler-onerror

**Comment by cvrebert** [comment]
https://dev.modern.ie/platform/status/runtimeerrorreportingerrorevent/

**Comment by leolux** [comment]
👍

**Comment by Connum** [comment]
+1

**Comment by webmaster-jmr** [comment]
+1

**Comment by trevorhreed** [comment]
I believe the instructions of "To vote this issue up or down, simply include +1 or -1 in your comment" only applied to Google Moderator. On Github, the way to up-vote is to "React" with a "Thumbs Up" on the original post.

Putting your upvote in a comment instead of a reaction doesn't allow project owners/contributors to find the most up-voted issues (i.e. https://github.com/Fyrd/caniuse/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by zwrawr** [comment]
bump

**Comment by cpplearner** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by PracticalCode** [comment]
Should this get approved, here's the Google Chrome info as best I know ([link to my StackOverflow answer](https://stackoverflow.com/a/53852089/1327508)) ::

I believe support started in Chrome v10 ([Chromium Issue 7771](https://bugs.chromium.org/p/chromium/issues/detail?id=7771)), but it looks as if "full" support with CORS support was resolved around Chrome 30+ ([Chromium Issue 159566](https://bugs.chromium.org/p/chromium/issues/detail?id=159566))

**Comment by saintbyte** [comment]
+1

**Comment by Fyrd** [comment]
Added a search result for this to redirect to the window "error" event entry via MDN: https://caniuse.com/?search=window.onerror
