### ISSUE TITLE
file input type supported browser

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1461]
file input type supported browser

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **pooja** on **2012-05-30**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by xml** [comment]
+1. 

AKA: the 'File Upload Control'. 

We have other items already that reference `input type=file` as an option ([such as](http://caniuse.com/#feat=input-file-accept)), but nothing that covers support for file input itself. The fact that we need to reference its subfeatures/params elsewhere is an excellent argument for including the base feature. 

It's important because it's a very viable tool for things like photo capture and upload from device in a mobile website or app. Normally, a requirement for photos would force you to use an app rather than web, with something like the Cordova camera plugin. But with `input type=file`, it becomes trivial in a web context. BUT, it only works on certain recent browsers... and I can't figure out which ones...

[Here's the spec](https://www.w3.org/TR/html-markup/input.file.html).

**Comment by Fyrd** [comment]
Available at https://caniuse.com/mdn-html_elements_input_input-file
