### ISSUE TITLE
html5 canvas.toblob

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1496]
html5 canvas.toblob

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Isius** on **2012-10-31**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Presumably this is covered by http://caniuse.com/#feat=canvas

**Comment by Fyrd** [comment]
Maybe, will need to investigate. Will leave it open for now.

**Comment by Secathor** [comment]
+1
canvas.toBlob not supported by Chrome 45 for example.

**Comment by holymonson** [comment]
+1
Browsers basic support of canvas doesn't count `toBlob()`, check https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by jmiller14** [comment]
+1

canvas.toBlob is not supported by iOS Safari either

**Comment by Ugoku** [comment]
[Patch landed in Webkit](https://bugs.webkit.org/show_bug.cgi?id=148878) in March of this year. I have no idea what Safari version supports this though...

Chrome supports this since [version 50](https://developers.google.com/web/updates/2016/03/canvas-toblob-in-chrome-50)

Edge only has `msToBlob` apparently (can't test right now) which behaves differently :(

**Comment by cvrebert** [comment]
* https://platform-status.mozilla.org/#htmlcanvaselement-toblob
* https://www.chromestatus.com/feature/4562033294966784

**Comment by kkomelin** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_htmlcanvaselement_toblob

**Comment by kkomelin** [comment]
@Fyrd Thanks!
