### ISSUE TITLE
display: -moz-box;   display: -webkit-box;   display: box;  Couldn't find it on the site :]

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1497]
display: -moz-box;  
display: -webkit-box;  
display: box;

Couldn&#39;t find it on the site :]

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __fiasst__ on __2013-07-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Schweinepriester** [comment]
Can be closed, because fixed by <http://caniuse.com/#feat=flexbox>.

```css
display: -moz-box;
display: -webkit-box;
display: box;
```

is old syntax. See

- <https://css-tricks.com/snippets/css/a-guide-to-flexbox/>
- <https://stackoverflow.com/questions/16280040/css3-flexbox-display-box-vs-flexbox-vs-flex>

    > These are different styles.
`display: box;` is a version of 2009.
`display: flexbox;` is a version of 2011.
`display: flex;` is the actual version.

    > Quote of Paul Irish
