### ISSUE TITLE
Emoji display support

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1522]
Emoji display support

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Benimation** on **2014-12-26**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1

**Comment by pathawks** [comment]
+1

**Comment by haampie** [comment]
+1

**Comment by Benimation** [comment]
+1

**Comment by charmesal** [comment]
+1

**Comment by timvloon** [comment]
+1

**Comment by BevansDesign** [comment]
+1

This is becoming more and more essential. Even in the past 6 months, I've noticed a significant increase in their use outside of text messages.

**Comment by Crissov** [comment]
It’s not quite clear what this issue is actually about. It could be asking which **color font format** a browser/platform supports (or if any), whether **variations selectors** 15/16 (U+FE0E/F) work correctly or **which characters have emoji glyphs** in default fonts.

JFTR, there are (at least) [4 OTF solutions][Twardoch] available: 

* Microsoft’s standardized [`COLR`][COLR]/[`CPAL`][CPAL] tables use standard True Type [`glyf`][glyf] or Postscript [`CFF `][CFF] outlines.
* Mozilla’s/Adobe’s standardized [`SVG `][SVG] table uses [SVG][SVGinOT] outlines and CSS Variables.
* Google’s standardized [`CBDT`][CBDT]/[`CBLC`][CBLC] tables use embedded PNG bitmaps. 
* Apple’s proprietary `sbix` table also embeds PNG images.

  [Twardoch]: http://blog.fontlab.com/font-tech/color-fonts/color-font-format-proposals/
  [SVGinOT]: http://www.w3.org/2013/10/SVG_in_OpenType/
  [OTF17]: http://www.microsoft.com/typography/otspec170/otff.htm
  [glyf]: http://www.microsoft.com/typography/otspec170/glyf.htm
  [CFF]: http://www.microsoft.com/typography/otspec170/cff.htm
  [COLR]: http://www.microsoft.com/typography/otspec170/colr.htm
  [CPAL]: http://www.microsoft.com/typography/otspec170/cpal.htm
  [SVG]: http://www.microsoft.com/typography/otspec170/svg.htm
  [CBDT]: http://www.microsoft.com/typography/otspec170/cbdt.htm
  [CBLC]: http://www.microsoft.com/typography/otspec170/cblc.htm

**Comment by EdoardoTona** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by tobireif** [comment]
The current maximum size for emoji would be useful info for web developers using CanIUse. Some data: https://tobireif.com/posts/maximum_font_size_for_emoji/

**Comment by swergas** [comment]
+1

**Comment by charisTheo** [comment]
+1

**Comment by kolosovsky** [comment]
+1

**Comment by Fyrd** [comment]
As mentioned in a [previous comment](https://github.com/Fyrd/caniuse/issues/1522#issuecomment-243964291) "emoji support" is pretty unclear and since general emoji support is more OS based then browser based I have added a search result at https://caniuse.com/#search=emoji to indicate this and will be closing this issue.
For support for each of the specific technologies behind color fonts, issue #1018 will act as parent issue, any other emoji-related tech should be filed as new issue.
