### ISSUE TITLE
Add removeAttribute support

### ISSUE THREAD

**Issue by schalkneethling** [Fyrd/caniuse#1662]
There seems to be pretty wide support for Element.removeAttribute but stats are unclear, outdated or not available so, would be useful to add this to !caniuse

**Comment by brennanyoung** [comment]
It's important to add this, since it is broken on MS Edge when removing boolean attributes such as hidden and selected. 

There is a workaround, though: Set the attribute to "false" and then remove it.

[https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12087679/](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12087679/)

**Comment by Schweinepriester** [comment]
<https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute>

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#search=removeAttribute

**Comment by brennanyoung** [comment]
Ach! The link from the caniuse resource to the MS bug report is now a 404.
