### ISSUE TITLE
Consistent filenames?

### ISSUE THREAD

**Issue by dandv** [Fyrd/caniuse#1710]
Looks like the JSON filenames are most of the time in [kebab-case](http://stackoverflow.com/questions/11273282/whats-the-name-for-dash-seperated-case).

Some are one word though, e.g. https://github.com/Fyrd/caniuse/blob/master/features-json/matchesselector.json

**Comment by Fyrd** [comment]
Mostly methods like `matchesSelector`, etc. are  converted to lowercase, hyphens are used to separate words for CSS properties and general API descriptions.

But since it's just a general unique identifier for various types of technologies (and because changes would break permalinks) I don't think there's much value in enforcing a particular format after they've been created.
