### ISSUE TITLE
window.scrollTo

### ISSUE THREAD

**Issue by MynockSpit** [Fyrd/caniuse#1760]
window.scrollTo

**Comment by Ugoku** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) says "DOM Level 0" under Specification, which according to [Quirksmode](http://www.quirksmode.org/js/dom0.html) means it's supported in Netscape 2+ which essentially means all browsers since then support this.

**Comment by Benimation** [comment]
-1

**Comment by ZLevine** [comment]
I request we reopen this -- while window.scrollTo is supported far back by many browsers, many versions (like Chrome on Android 6-8) throw errors when you use this format:

```
// this changes the scrolling behavior to "smooth"
window.scrollTo({
    top: 1000,
    behavior: "smooth"
});
```

Instead of using:

```
window.scrollTo( 0, 1000 );
```

Some of these errors include:

```
Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': 2 arguments required, but only 1 present.
Uncaught TypeError: Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided.
```

I'm testing whether providing a third argument (like `left`) resolves this, but I think this belongs here.

**Comment by xianshenglu** [comment]
```javascript
window.scrollTo( 0, 1000 );
```
I just tested IE11 and Edge,supported. However , it will scroll to top if you pass an object .
