### ISSUE TITLE
Add theme-color Meta Tag

### ISSUE THREAD

**Issue by FreddyFY** [Fyrd/caniuse#1831]

**Comment by Ugoku** [comment]
+1

**Comment by cvrebert** [comment]
-1

**Comment by navarr** [comment]
+1

Would be very interesting to have a list of browsers that support theme-color in some form or fashion.

**Comment by jankeromnes** [comment]
+1

Quick research:
- Looks like a spec: https://github.com/whatwg/meta-theme-color
- Supported since Chrome 39 on Android Lollipop: https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android?hl=en
- Supported since Firefox 34 and Firefox OS 2.1: https://bugzilla.mozilla.org/show_bug.cgi?id=1013913
- Windows 8 / IE10 have something called `msapplication-TileColor`: https://blogs.msdn.microsoft.com/ie/2012/06/08/high-quality-visuals-for-pinned-sites-in-windows-8/
- Firefox 33 for Android added support for the Microsoft thing: https://digdug2k.wordpress.com/2014/07/30/better-tiles-in-fennec/

**Comment by tobias47n9e** [comment]
+1

**Comment by nolanlawson** [comment]
Now an official part of the standard: https://github.com/whatwg/html/commit/05e4a1f6c4941273baa647b8e889d2db7fd9bd88

**Comment by slightlyoff** [comment]
:+1:

**Comment by codynguyen1116** [comment]
+1

**Comment by martijn80** [comment]
+1

**Comment by ArekJanik** [comment]
+1

**Comment by Darex1991** [comment]
+1

**Comment by eXistenZNL** [comment]
+1!

**Comment by Benimation** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by dampee** [comment]
👍

**Comment by dbs** [comment]
+1

**Comment by coliff** [comment]
+1
I can find no evidence of `<meta name="theme-color" content="#ff69b4">` doing anything on Android 6 (Marshmallow) with Chrome 59, Firefox 55, or Opera 42. If anyone knows of this feature working / being supported in any browser pls post here.

**Comment by Benimation** [comment]
It changes the UI color in Google Chrome on Android:

![screenshot_2017-07-10-20-42-56](https://user-images.githubusercontent.com/5503862/28034337-28e43eb4-65b1-11e7-9f84-2c88a5225fb3.png)
![screenshot_2017-07-10-20-45-48](https://user-images.githubusercontent.com/5503862/28034336-28d51cea-65b1-11e7-9566-6cf9c802b598.png)


I've also seen it changing the color of the tabs in the desktop version of Yandex Browser.

**Comment by chrisblakley** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=meta-theme-color
