### ISSUE TITLE
Yes please

### ISSUE THREAD

**Issue by 1j01** [Fyrd/caniuse#1890]
> [Standard events (click, change, etc) that have been supported since forever aren't on the site. Caniuse is intended for "newer" technologies with that have varied support.](https://github.com/Fyrd/caniuse/issues/1847#issuecomment-136221727)

What, are we suppose to look in our history books before consulting caniuse? People don't automatically know what technologies are "newer" or how "varied" support is for a feature.

Please add simple "Yes" pages for features that are widely supported. This would be *incredibly useful*. It would also be absolutely *delightful* and would save a lot of peoples' time.

**Comment by Fyrd** [comment]
Fair enough, and I mostly agree. Caniuse started out with the intent to add clarity to what latest tech was supported by what browsers...since then it's grown in both in database size as well as popularity to the point at which people seem to have started to expect it to include everything.

Because of this I actually started including search results for older features, much like you suggest (see [example](http://caniuse.com/#search=getelementbyid), however it doesn't include everything. I'm happy to include those on a case by case basis, and should do so for the `unload` event too.

So I'll close this since what you ask for basically exists and perhaps create a new label for requests that should be added to the "Yes" list.

**Comment by 1j01** [comment]
@Fyrd Okay, but keep in mind that a big simple "Yes" would make these pages fun. It could precede the list or other more detailed information or stand alone because that's all the information you really need.

**Comment by dr-dimitru** [comment]
Or some tech and standards can become deprecated. It is good to know when it was deprecated and which platforms is still supporting it.
