### ISSUE TITLE
Incorrect `Current Chrome status` URLs

### ISSUE THREAD

**Issue by MayhemYDG** [Fyrd/caniuse#2061]
@Fyrd 
For example: http://caniuse.com/#feat=css-variables
It links to: https://www.chromestatus.com/features/6401356696911872
When it should instead link to: https://www.chromestatus.com/feature/6401356696911872

`/features/` -> `/feature/`

**Comment by jpmedley** [comment]
Can you describe the scenario where your first link is failing.  If I right-click and open the first one it just opens chromestatus.com. If I click it normally, the correct item opens. 

I think this is correctable by chromestatus.com itself. Since such links are likely scattered all over the internet, I'm going to file a bug.

**Comment by MayhemYDG** [comment]
Mmh I can't reproduce it anymore.
I think it was because the list was jumping around as it was loading. Right now if I just load the page and scroll up, the list will jump down first.

**Comment by jpmedley** [comment]
Which browser?

**Comment by MayhemYDG** [comment]
Chrome 46. Happens as well on Firefox and Safari so I'm guessing this is a bug in the page's JS.
It also jumps when you scroll down after a while. Need a video to demonstrate?

I'll close as it's not a issue with caniuse.
