### ISSUE TITLE
Add CSS3 feature `text-orientation`

### ISSUE THREAD

**Issue by blueset** [Fyrd/caniuse#2077]
> This property specifies the orientation of text within a line. Current values only have an effect in vertical typographic modes: the property has no effect on boxes in horizontal typographic modes.
> — [CSS Writing Modes Level 3, W3C Candidate Recommendation](https://drafts.csswg.org/css-writing-modes-3/#text-orientation)

Related links
- [`text-orientation`, CSS Writing Modes Level 3, W3C Candidate Recommendation](https://drafts.csswg.org/css-writing-modes-3/#text-orientation)
- [`text-orientation`, Mozilla Developers Network](https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation)

**Comment by bigandy** [comment]
Has been in [Firefox by default](https://developer.mozilla.org/en/docs/Web/CSS/text-orientation#Browser_compatibility) since version 51 and in Chrome since version 48. Would be excellent to see it added to caniuse!

**Comment by meyerweb** [comment]
Adding my vote to this request.  It appears to be fully supported in Firefox and Chrome, supported in Safari with `-webkit-` prefix, unsupported in Opera so far as I can tell.  Don’t have Edge or IE11 currently handy.  See http://meyerweb.com/eric/css/tests/css3/show.php?p=text-orientation for a test.

**Comment by jensimmons** [comment]
+1 

People aren't talking about `text-orientation` much yet, but they should be. It's an integral part of Writing Modes, something else I would like to see authors use more often.

**Comment by huijing** [comment]
+1

`writing-mode` and `text-orientation` are meant to be used together. Basic support, for the values `mixed` and `upright`, as @bigandy mentioned, has been supported since Chrome 48 and Firefox 51.

<code>text-orientation: mixed</code>
<img width="45" alt="mixed" src="https://cloud.githubusercontent.com/assets/1461498/26030628/b4a0e1cc-388a-11e7-9661-cd1882653268.png">

<code>text-orientation: upright</code>
<img width="53" alt="upright" src="https://cloud.githubusercontent.com/assets/1461498/26030629/b57260da-388a-11e7-96af-157363641eea.png">

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-text-orientation

**Comment by jensimmons** [comment]
Thanks for getting this done! I was needing it for a slide early tonight... and now I've got it. 👯
