### ISSUE TITLE
Add PhantomJS

### ISSUE THREAD

**Issue by HamsterCoder** [Fyrd/caniuse#2106]
I am not sure if this falls in Can I Use scope. But for me It will be very usefull to see support for various Javascript APIs.

**Comment by Ugoku** [comment]
[Like this?](http://kangax.github.io/compat-table/es6/) :)

**Comment by HamsterCoder** [comment]
Reading my thoughts, lol =)

**Comment by aendrew** [comment]
I came to the queue to open this exact issue, only to find HamsterCoder beat me to it by a day. :smile: 

As useful as Kangax's compatibility tables are and as big of a can of worms as it would be to open up by adding one non-standard browser (like PhantomJS) caniuse, I think it would be a very useful addition. Why?

1. PhantomJS (particularly 1.x) has a lot of features not available on modern browsers, and PhantomJS2 seems like it's still a ways away from wide release.
2. PhantomJS is used extensively in automated testing, and having it on caniuse will alert developers to possible incompatibilities while they're developing (i.e., instead of checking caniuse while doing front-end development, being frustrated by tests not working in PhantomJS, checking Kangax and realising PhantomJS 1.x doesn't support, say, MutationObserver, and then taking action to correct the tests, developers will realise that PhantomJS doesn't support that functionality from the first step and then will either not use the technology or preemptively install a polyfill or whatever).
3. No other JS-based browser tech comes close to the ubiquity of PhantomJS, excepting maybe Electron, but that's effectively just Webkit. 

So, :+1: here.

**Comment by tregusti** [comment]
:+1:

**Comment by FezVrasta** [comment]
I'd love to get informations about PhantomJS compatibilities on Can I Use!

**Comment by danielcompton** [comment]
Phantom JS development has been [suspended](https://github.com/ariya/phantomjs/issues/15344), and the project has been archived. Given that, does it make sense to close this issue for now until/if development is commenced again?

**Comment by Fyrd** [comment]
Closing per last comment.
