### ISSUE TITLE
Fragment identifers support

### ISSUE THREAD

**Issue by fetis** [Fyrd/caniuse#2252]
I want to open this issue regarding to my PR
https://github.com/Fyrd/caniuse/pull/2220

Despite of it was merged, i think that caniuse still has incorrect data. So there's no iOS support at the moment for this.

@Fyrd can you share your tests? so I (and maybe somone else) can check is current support table really true.

**Comment by Fyrd** [comment]
Hi @fetis, thanks for the reminder on this! Just tested and you're right, while it was working in Safari 8 and iOS 8 it seems support was removed on Safari 9 & iOS 9. Seeing support be removed is pretty rare, which is why I overlooked that in this case.

btw, in case you're interested I've made a copy of my original test which intermittently appears to be passing for backgrounds in Chrome (tested in Chrome 48/Mac) (first 2 squares) at http://tests.caniuse.com/svg-fragment.html the new test is at http://tests.caniuse.com/?feat=svg-fragment
