### ISSUE TITLE
Please add support for getTimezoneOffset()

### ISSUE THREAD

**Issue by valnub** [Fyrd/caniuse#2287]

**Comment by cvrebert** [comment]
Since it was apparently [first defined in ECMAScript 1st Edition](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset#Specifications), I would suspect it's supported "universally".

**Comment by humancalendar** [comment]
"Supported" is a bit of a misnomer.  This function was incredibly buggy across browsers in 2002-2003 so I've avoided it since.  I recently thought about using it again (hence ending up here), but it looks like even as Chrome had problems as late as 2013 with it:

https://code.google.com/p/chromium/issues/detail?id=294037

**Comment by Schweinepriester** [comment]
Available via MDN now: <https://caniuse.com/mdn-javascript_builtins_date_gettimezoneoffset>

Doesn't mention the problems though…

**Comment by Fyrd** [comment]
Related Chromium bug was fixed back in 2018: https://bugs.chromium.org/p/v8/issues/detail?id=3547

So going to go ahead and close this.
