### ISSUE TITLE
Adding Silverlight usage stats

### ISSUE THREAD

**Issue by Antronin** [Fyrd/caniuse#2355]
Please add Silverlight usage stats. It would be useful to see how deprecation in Chrome, Firefox and IE is spreading. Thanx.

**Comment by Schweinepriester** [comment]
<https://en.wikipedia.org/wiki/Microsoft_Silverlight>:

> Microsoft terminated support for Silverlight on [Internet Explorer 11](https://en.wikipedia.org/wiki/Internet_Explorer_11) (the last remaining web browser still supporting Silverlight) on October 12, 2021.

This table covered the deprecation spread nicely: https://en.wikipedia.org/wiki/Microsoft_Silverlight#Desktop_computers

A search result for Silverlight linking to Wikipedia could be nice, but other than that I think this issue is now obsolete.

**Comment by Fyrd** [comment]
Looking at my recent logs there's about 2 searches for silverlight a month so probably not even worth that. Seems safe to close this issue.
