### ISSUE TITLE
Why only latest version of Chrome for Android?

### ISSUE THREAD

**Issue by KODerFunk** [Fyrd/caniuse#2413]
Why only latest version of Chrome for Android in all stats?
I use https://github.com/postcss/autoprefixer for polish my styles for Cordova-based application with Crosswalk-webview (16 / android chrome **45**). 
autoprefixer use browserlist, browserlist use caniuse, caniuse take only version **49**, and i cant produce correct stylesheets for my amazing app)

**Comment by Fyrd** [comment]
Various reasons:
- Caniuse's usage statistics source Statcounter, doesn't include usage data for individual versions of mobile browsers (iOS & Android usage comes from another source). Not having such data will likely lead to confusion as users expect there to be numbers there. 
- I like to be able to test on older browser versions. That's easier for desktop browsers, much harder for mobile browsers.
- The support data is largely the same as the desktop equivalent anyway, so the value is limited.
- Including more rapid release versions for mobile browsers means more data to keep up with, slowing down downloads and other processes.

At some point I may add them (or just a few more versions) but it's not a priority. Keep in mind the caniuse site data is primarily intended to serve the site, not dependencies.

**Comment by FStefanni** [comment]
Hi,

I just want to note a case where being able to check features for older browsers on Android is useful.

The scenario is when for some reason a browser cannot be updated. The most common is when a device (usually a tablet)
is "kiosked", i.e. the operative system is locked by a special app, in order to allow users to perform only some actions.
A practical example could be a tabled sold with a monitoring system of a house: the company creating the monitoring system will allow that tablet to execute only few selected apps, so that the tablet will be not usable as a generic normal tabled. The updates are performed only when the company will release a new update.

In this scenario, the special apps could open an embedded browser, pointing to a dashboard running in cloud: and this is when the company's developers would like to know whether the features they are using will require an update of the tablet.

This is a scenario similar of what we have at the company I am working for.
So I hope that somehow in a future the database will include also the information about the older Android browsers.

Regards

**Comment by nightpool** [comment]
@Fyrd Can we please get the ability to separate out Chrome on Android support when we're using our own stats? It's much easier now then it was in the past to test on older versions of Chrome on Android, since the APKs are archived and many sites provide the ability to launch them.
