### ISSUE TITLE
IntersectionObserver

### ISSUE THREAD

**Issue by arturparkhisenko** [Fyrd/caniuse#2425]
Spec: https://github.com/WICG/IntersectionObserver/
Mdn: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

Chrome: 51+ https://www.chromestatus.com/feature/5695342691483648
Opera: 38+
Edge: [feature request link](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/13407852-intersectionobserver) and [Roadmap link](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/intersectionobserver/) Status: In Development
FireFox: https://bugzilla.mozilla.org/show_bug.cgi?id=1243846
WebKit(Safari): https://webkit.org/status/#specification-intersection-observer

**Comment by orzage** [comment]
+1

**Comment by nextPrime** [comment]
+1

**Comment by jrstanley** [comment]
FireFox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1243846

**Comment by cvrebert** [comment]
+1

**Comment by jrstanley** [comment]
+1

**Comment by nextPrime** [comment]
Under Consideration with Medium priority by Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/intersectionobserver

**Comment by nullbert** [comment]
+1

**Comment by jhiggins-thrillist** [comment]
+1

**Comment by okor** [comment]
+1

**Comment by rjgotten** [comment]
Something to make mention of:

Chrome's implementation is fundamentally broken, atleast up to the current 53.0.2783.2 dev-m version. The way it observes threshold changes and enqueus change records does not adher to spec.

According to spec, a change record is supposed to be enqueued when the active threshold changes. 
The active threshold is computed as follows:
* when intersection ratio is 0, the threshold is 0
* when intersection ratio is 1, the threshold is the length of the thresholds array (i.e. one index greater than the number of thresholds)
* otherwise, the threshold is the index of the first threshold with a value **greater than** the intersection ratio.

(Source: [Draft spec, section 3.2.5 - algorithm step 3.2.8](http://rawgit.com/WICG/IntersectionObserver/master/index.html#update-intersection-observations-algo))

For the default `{ threshold : [0]}` setting, Chrome currently already enqueues a change record when the intersectionRatio is exactly 0. This makes it impossible to use a simple `intersectionRatio > 0` test to determine if an element just became visible or invisible and have it work correctly in any reliable way.

**Comment by cvrebert** [comment]
@rjgotten Is there a [Chrome bug report](https://crbug.com) for that?

**Comment by cvrebert** [comment]
@rjgotten I filed https://crbug.com/646202 based on your description. If you have further details (or a testcase), it would be great if you could post them on that bug.

**Comment by cvrebert** [comment]
WebKit: In Development: https://webkit.org/status/#specification-intersection-observer

**Comment by mkurz** [comment]
Edge: Intersection Observer is In Development - https://github.com/MicrosoftEdge/Status/pull/464

**Comment by cvrebert** [comment]
@rjgotten Apparently that's working as intended; see https://bugs.chromium.org/p/chromium/issues/detail?id=646202#c5

**Comment by rjgotten** [comment]
> Apparently that's working as intended

Yeah; this is a case of Google retro-actively messing with their own spec.
Note also: https://github.com/WICG/IntersectionObserver/issues/156

**Comment by lingtalfi** [comment]
+1

**Comment by rjgotten** [comment]
@cvrebert 

After some further digging, I'm inclined to believe that this is not working as intended at all, and that the engineer replying in that tracker issue is doing little other than offering a shoddy workaround wrapped as an end-solution.

If the use of the `Number.MIN_VALUE` value to detect if an element is intersecting the target bounds for *any* amount of non-zero intersection, would indeed by design; and if it should indeed be used instead of the `0` value that Google's own spec states, then *why* is the default thresholds value in Chrome's implementation still a known-broken value of `[0]`?

(Yeah; check that for yourself: `new IntersectionObserver(function(){}).thresholds` )

**Comment by AdamModus** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=intersectionobserver

**Comment by SuperPat45** [comment]
+1
