### ISSUE TITLE
Multicolor Glyph support (COLR/CPAL)

### ISSUE THREAD

**Issue by xyproto** [Fyrd/caniuse#2458]
Some browsers supports multicolored glyphs, such as the "COLR/CPAL" format.

When can I use that?

Here is one test: https://pixelambacht.nl/demo/color-font-test.html
And here is an article: https://pixelambacht.nl/2014/multicolor-fonts/

Cheers!

**Comment by eosrei** [comment]
+1 

> The vote count is based on +1s in each issue's comments

src: http://caniuse.com/issue-list

**Comment by Crissov** [comment]
May be relevant for emoji support. #1522

**Comment by tobireif** [comment]
Newer URL: https://pixelambacht.nl/chromacheck/

**Comment by tobireif** [comment]
+1

**Comment by tphinney** [comment]
This isn't a subset of #1018 , it's the exact same thing.

**Comment by Crissov** [comment]
@tphinney is right unless we treat this issue as limited to COLR/CPAL.

**Comment by tphinney** [comment]
Well, the request was "such as" not "specifically."
Since COLR/CPAL is not the best supported color font format, and as support for the four variant formats is quite different, but ~ similar in extent (although the smart money would be betting on SVG OpenType in the long run), it would be silly for CanIUse to choose to enumerate the COLR/CPAL format without the others, at this time.

**Comment by Fyrd** [comment]
Re-purposing this issue to be specifically for COLR/CPAL, subset of #1018

**Comment by yisibl** [comment]
> but ~ similar in extent (although the smart money would be betting on SVG OpenType in the long run), it would be silly for CanIUse to choose to enumerate the COLR/CPAL format without the others, at this time.
@tphinney 

COLR/CPAL is currently compatible with almost all mainstream browsers, which is a very important feature. [As Chrome will soon support the COLR v1 specification](https://groups.google.com/a/chromium.org/g/blink-dev/c/XIXudwZdr44), it will also support gradients. It is very reasonable that we separately list the compatibility of COLR/CPAL.

**Comment by yisibl** [comment]
I am going to submit a PR for the COLR table, who can help review?

**Comment by tphinney** [comment]
> COLR/CPAL is currently compatible with almost all mainstream browsers, which is a very important feature.

It’s as if things have changed since 2017! No question that COLR/CPAL is the leading color font format. With support for gradients coming, that should cement the lead.

That said, covering color font formats that are not universally supported is as useful as covering those that are nearly so. With SVG color fonts being so widely supported in desktop design apps used for web mockups, web designers may easily be surprised by this dichotomy in support....

**Comment by yisibl** [comment]
I submitted a PR for the COLR font: https://github.com/Fyrd/caniuse/pull/5915

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/colr

**Comment by Fyrd** [comment]
Fun fact: also supported on KaiOS:
![Screenshot_20210525-122249](https://user-images.githubusercontent.com/432336/119556600-16104680-bd54-11eb-8898-28628cab6848.png)
