### ISSUE TITLE
Add referrerpolicy attribute

### ISSUE THREAD

**Issue by codefir** [Fyrd/caniuse#2654]
https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery-referrer-attribute

**Comment by cvrebert** [comment]
Theoretically http://caniuse.com/#feat=referrer-policy ought to include this.
Dunno if the attribute was included in the testing though.

**Comment by piotrekkaminski** [comment]
Referrerpolicy support, eg as an iframe attribute, would be helpful

**Comment by Calico90** [comment]
+1

**Comment by hartman** [comment]
@cvrebert To me it seems that any browser that is still on the 'older draft' doesn't support neither the header nor the attribute.

### attribute
I know that the attribute became available in Chrome in version 51: https://bugs.chromium.org/p/chromium/issues/detail?id=490608

For Firefox it's starting version 50, per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

### referrer policy header
Chrome apparently since version 56 https://bugs.chromium.org/p/chromium/issues/detail?id=619228

Firefox, version 50, for the older policies and version 52 for the newer policies, per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by claudepache** [comment]
+1

**Comment by cocojiambo** [comment]
+1

**Comment by philwareham** [comment]
I think Safari v12.1 supports `referrerpolicy` attributes on at least _some_ elements, can't find much detail on its support so far though - apart from a vague reference in the [Tech Preview 78 Release Notes](https://developer.apple.com/safari/technology-preview/release-notes/).

**Comment by Schweinepriester** [comment]
+1

<https://webkit.org/blog/9497/release-notes-for-safari-technology-preview-89/>

> Added `referrerpolicy` attribute support for `<script>` elements ([r247509](https://trac.webkit.org/changeset/247509/webkit/))
