### ISSUE TITLE
"Current Aligned" view to show last unsupported browser if currently supported

### ISSUE THREAD

**Issue by bytesnz** [Fyrd/caniuse#2659]
It would be great if the currently aligned could show the last browser that didn't support the feature, or any partial supports. As an example, in the IE column, [instead of show IE8], show IE9 (as this was the last version to not support it).
![image](https://cloud.githubusercontent.com/assets/1755886/17054400/dd73d1ba-4ffe-11e6-888c-dc08b0a6b3c0.png)

**Comment by Fyrd** [comment]
For what purpose though? If you care about IE9 you can decrease the usage slider until it shows up. That way it'll also show other browser versions with a usage % you'd be equally interested in supporting.

**Comment by bytesnz** [comment]
It would mean that in the default view (current aligned) you would be able to see both the current version support and (at least) the first version that didn't support it without having to fiddle with the view. Why is IE8 shown in the current aligned view anyway instead of more recent previous versions?

**Comment by Fyrd** [comment]
The new view mode rework now has "Show all" as the default view, which will show all versions and their different degrees of support.

Also to (belatedly) answer the last question, when in the "filtered" mode, browser versions only appear when they have a certain usage %, at the time IE8 was used more than IE9 & 10 which is why those were hidden but IE8 was not.
