### ISSUE TITLE
Suggestion: Int64 UInt64 (Firefox only AFAIK)

### ISSUE THREAD

**Issue by sfinktah** [Fyrd/caniuse#2714]
... and only since your web page took me here to ask.

https://developer.mozilla.org/en/js-ctypes/js-ctypes_reference/UInt64

**Comment by GPHemsley** [comment]
That link is dead, perhaps because EcmaScript/JavaScript eventually implemented something similar.

Such features are now covered by MDN data:
https://caniuse.com/mdn-javascript_builtins_dataview_getbigint64
https://caniuse.com/mdn-javascript_builtins_bigint64array
https://caniuse.com/mdn-javascript_builtins_dataview_getbiguint64
https://caniuse.com/mdn-javascript_builtins_biguint64array

(via mdn/browser-compat-data#4248)
