### ISSUE TITLE
When will https://github.com/Fyrd/caniuse/blob/de86276b1c8f29dcf4db2c42358558c9256670fe/features-json/urlsearchparams.json show up?

### ISSUE THREAD

**Issue by ebidel** [Fyrd/caniuse#2834]

**Comment by Fyrd** [comment]
See my comments at https://github.com/Fyrd/caniuse/pull/2724 on why it takes time before features show up.

That said, since according to #1312 at least this does appear to be a requested feature, I went ahead and did the research, so with updates it's now available at http://caniuse.com/#feat=urlsearchparams

**Comment by ebidel** [comment]
Coil. Thanks!
