### ISSUE TITLE
Add color-mod() | color() function - CSS Color Module Level 4

### ISSUE THREAD

**Issue by astoilkov** [Fyrd/caniuse#2864]
I suggest adding [color-mod() | color() function part of CSS Color Module Level 3](https://drafts.csswg.org/css-color/#modifying-colors) specification.

**Comment by Schweinepriester** [comment]
+1

**Comment by mkurz** [comment]
+1

**Comment by svgeesus** [comment]
-1
The color-mod section of the spec is very draft-ish and likely to be substantially rewritten.

**Comment by cherscarlett** [comment]
While this is still in draft, because polyfill tools are using it, it can be super confusing for developers who aren't a part of tool selection to understand that it's not actually a part of CSS yet. Adding in a caniuse that explains something like this for these really common polyfills is worth a conversation.

**Comment by GreLI** [comment]
FYI, there is no more `color-mod()` function, and `color()` is for specific colors from color profiles. There is no color modifying options like it was a couple of years before. So, this is no go.

But generally, it's worth to add CSS4 Color Module support like 8-digit hex color, `rgb(num num num / alpha)`, `hwb()` and so on. Some browser already support it.

**Comment by Fyrd** [comment]
Going to go ahead and close this issue since this is no longer part of the specification. Feel free to open new issues for other CSS4 Color Module sections if needed.
