### ISSUE TITLE
IE10 WebSocket support

### ISSUE THREAD

**Issue by halt-hammerzeit** [Fyrd/caniuse#3130]
For some reason IE10 was left out of the WebSocket support data:
http://caniuse.com/#search=websocket
I googled a bit and they say it is working in IE10.
Should IE10 be added to the list of supported browsers then?

And why the strange ancient "Opera Mini" thing?
Maybe you should have got rid of it for ages by now?

**Comment by Fyrd** [comment]
By default only browsers with 0.5% usage are shown. IE 10 is not listed by default because it has low global usage (0.24%). Click on "show all versions" or adjust the slider under Settings to see it.

Opera Mini is a very popular browser in some countries, primarily in Africa. In Nigeria for example its usage is at 53%, way above any other browser.

**Comment by halt-hammerzeit** [comment]
Oh, didn't imagine IE10 is actually that unpopular.
That's an argument for my future talks with project manager.
Thx for the clarification.
I'm still not a fan of you having Opera Mini there though, it has just "UNSUPPORTED" written all over it.
But that's your decision to make.
