### ISSUE TITLE
Can we add, flow-root and clearfix?

### ISSUE THREAD

**Issue by okbrown** [Fyrd/caniuse#3136]
Wanted to know which browsers `flow-root` worked for but no results returned. I also tired `clearfix` but that also did not return anything.

Is this the correct process to request the additions of these two?

**Comment by Schweinepriester** [comment]
Principally this is the right process to request additions, though in this case the property already had been requested in #2999 and even added in #3069, however is not showing up yet, since @Fyrd still has to review the data.

Therefore maybe (additionally) comment in those tickets or he will use this issue as request for review (alike #2766 for FLAC).
In latter case: +1 ;)

**Comment by okbrown** [comment]
Aha! Thanks I will reply there instead, thanks!

**Comment by jhpratt** [comment]
Yeah, I just did this a little bit ago as after the discussion on WICG Discourse. It's pending data review, although no browser supports it (and I'm 99% on this).

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=flow-root (a search for clearfix will find it too)

**Comment by okbrown** [comment]
Thanks!!
