### ISSUE TITLE
Add text-underline-position property

### ISSUE THREAD

**Issue by kojiishi** [Fyrd/caniuse#3183]
The [`text-underline-position`](https://drafts.csswg.org/css-text-decor-3/#propdef-text-underline-position) property is in CR spec.

[Quick test](http://jsbin.com/mamojo/edit?html,output) indicates:

- WebKit supports with prefix.
- Blink added this in [M57](https://www.chromestatus.com/features/5766823203045376), currently in beta.
- MSDN [says](https://msdn.microsoft.com/en-us/library/ms531176.aspx) it supports old syntax with prefix, but I can't see it working in IE/Edge.
- Gecko has [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=770780), though not active these days.

**Comment by Ugoku** [comment]
+1

Didn't know this was a thing, cool!

**Comment by gretencord** [comment]
+1

**Comment by squarecandy** [comment]
+1

**Comment by shockthetoast** [comment]
+!

I just found out about this, and am having trouble finding proper browser support information. MDN's documentation lists many browser/property combinations as "unknown". It would be really helpful to have this in caniuse.

**Comment by JayBox325** [comment]
+1

**Comment by lw-nc-usa** [comment]
Webkit/Safari 12.1 now supports **text-underline-offset** and **text-decoration-thickness**.

**Description:** 
The text-underline-offset allows for placing an underline at a specific location below the baseline. The text-decoration-thickness property specifies the thickness using a length value — a number followed by a unit (e.g. 1px or 0.5em). Rather than using absolute lengths, using em units in both of these properties is preferable here so that the line thickness and offset scales with the font size. You can also specify from-font to both of these properties which will pull the relevant metric from the used font file itself.

**Documentation:** 
https://webkit.org/blog/8718/new-webkit-features-in-safari-12-1/

**Comment by jensimmons** [comment]
We should add both `text-decoration-thickness` and `text-underline-offset`. As stated above, both are now supported in Safari 12.1+. And we are implementing them in Firefox.

**Comment by dippas** [comment]
Here is the current support data according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position#Browser_compatibility)

![image](https://user-images.githubusercontent.com/10220287/60708563-43586f00-9f06-11e9-9973-05bbed3f3917.png)

**Comment by jensimmons** [comment]
Ah, `text-underline-position` and `text-underline-offset` are two different things. I'll go open a different issue for the latter.

**Comment by kiding** [comment]
This feature will be shipped with [Chrome 87](https://blog.chromium.org/2020/10/chrome-87-beta-webauthn-in-devtools.html).

**Comment by Fyrd** [comment]
Available at https://caniuse.com/mdn-css_properties_text-underline-position
