### ISSUE TITLE
Why are old browsers still listed?

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#3245]
General question: IE versions start at 6. IE 1, 2, 3, 4, 5, 5.5 are not listed. But Firefox 2 (released October 2006) and Chrome 4 (released January 2010) _are_. Is there a reason for this? Choosing "usage relative" mode makes it quite clear those versions aren't in use anymore, so why show them? Why not start the latest +- 10 versions for those browsers?

This could mean a lot of notes for old browsers can be deleted, giving a much cleaner and clearer look.

So, is there a reason for this? If not, would you consider this?

**Comment by Fyrd** [comment]
The oldest versions that appear are the ones that were still being used back when I started the site in 2008. Since then I've only added versions, never removed them.

While I've considered removing more of the older ones for the reason you point out, it gets a bit more complicated when you consider regional data. Just because the default "Global" data suggests it's not used doesn't mean it isn't in some particular region. For example Firefox 2 has 0.23% usage in Africa, which is similar to IE10 usage globally (0.24%).

There's also some people who just like to see at what version a feature started being supported, so hiding them would remove them from being able to do so.

Anyway, old, unused browsers _are_ hidden by default. That's the whole reason the default view only shows 0.5% or above (adjustable by the slider under Settings), it solves the problem you describe. Also notes from older versions are hidden in this mode too. Is there a reason this solution doesn't work for you in achieving the cleaner & clearer look?

**Comment by Ugoku** [comment]
> For example Firefox 2 has 0.23% usage in Africa, which is similar to IE10 usage globally (0.24%).

Oh wow, I definitely didn't expect that.

> Anyway, old, unused browsers are hidden by default. That's the whole reason the default view only shows 0.5% or above (adjustable by the slider under Settings)

I had no idea it worked that way. That completely solves my problem indeed. It hides the notes that are not relevant and everything. Awesome :) Thanks for the explanation!
