### ISSUE TITLE
Make 'show all' appear in URL so I can link to it.

### ISSUE THREAD

**Issue by jpmedley** [Fyrd/caniuse#3395]
I write materials on [developers.google.com](https://developers.google.com/web/). When I reference browser support I (and others in my group) like to link to caniuse.com rather than list data that will soon be out of date. Currently, to see the UC and other browsers common in other parts of the world, I have to click a button after arriving a page. It would be nice if I could include my friends in the far east without special instructions that say 'go here and click this'. (We try to reduced friction wherever we can.)

**Comment by evalica** [comment]
The "Show all" is really tricky. I referred someone to caiuse and the only value displayed for IE was IE11 in case of "calc()". They didn't know about the "Show all", so they thought IE11 was the only supported browser, although this unit works in other browsers too. Since they were looking for a solution for IE10, they looked for a replacement.

**Comment by evalica** [comment]
Issue related/duplicate to https://github.com/Fyrd/caniuse/issues/2920

**Comment by Fyrd** [comment]
This is now possible by setting up a browser set (under Settings) and using the link the Import/Export button. That'll let you determine the exact browsers visible when you share. See https://caniuse.com/feed/159 for details and let me know if that works for you!
