### ISSUE TITLE
Show minimum supported version of a feature

### ISSUE THREAD

**Issue by martijnkorteweg** [Fyrd/caniuse#3922]
currently it shows the latest version of a browser that has support

as an example
https://caniuse.com/#search=first-child

this will come up for IE11 as supported, and is also supported since IE7 altho not displayed till you click "show all". It would be amazing to see the minimum version, when a feature was introduced.

**Comment by gitgrimbo** [comment]
I agree. "show all" is a bit painful to navigate when there is a large time/version gap between `browser-version-that-first-supported-feature-x` and `latest-version-of-browser-that-supports-feature-x`.

For example, I want to add a service worker to a site and so I wanted to try and determine earliest browser versions that supported this, in order to determine what other browser features were supported by that version (so I could also use them without transpilation in my service worker JS file).

-----

Having looked at [caniuse-cmd](https://github.com/sgentle/caniuse-cmd) I can get the info I'm looking for. Would be nice if the website could show this too.

`caniuse serviceworkers`

E.g. I can see from the following that Chrome 45+ fully supports service workers.

```
Service Workers √ 84.43% Θ 0.2% [W3C Working Draft]
  Method that enables applications to take advantage of persistent background
  processing, including hooks to enable bootstrapping of web applications while
  offline. #JSAPI

  IE ×
  Edge × 12+ × 15+² √ 17+
  Firefox × 2+ × 33+¹ √ 44+ √ 45+³ √ 46+ √ 52+³ √ 53+
  Chrome × 4+ Θ 40+ √ 45+
  Safari × 3.1+ √ 11.1+
  Opera × 9+ Θ 27+ √ 32+

    ¹Partial support can be enabled in Firefox with the
    `dom.serviceWorkers.enabled` flag.
    ²Available behind the "Enable service workers" flag
    ³Disabled on Firefox ESR, but can be re-enabled with the
    `dom.serviceWorkers.enabled` flag
   ⓘ  Details on partial support can be found on [is ServiceWorker
   Ready?](https://jakearchibald.github.io/isserviceworkerready/)
```

**Comment by Fyrd** [comment]
The issue described here is now fixed with the new view mode rework: "Show all" is now the default and combines multiple versions into one, making it much easier to see when support changed.
