### ISSUE TITLE
treeWalker / nodeIterator support needs to be added

### ISSUE THREAD

**Issue by ryanhemphill** [Fyrd/caniuse#3940]
the JavaScript support for treeWalker and nodeIterator are becoming increasingly important for DOM manipulation, especially in establishing complex range objects when dealing with the Selection API, which you currently DO list support. Without these two, nothing particularly sophisticated can be done with Selection API (speaking as someone who tried). 

I feel they should be included in the future. Thanks for listening.

**Comment by cvrebert** [comment]
i.e. the DOM traversal APIs: https://dom.spec.whatwg.org/#traversal

* https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker

**Comment by filbo** [comment]
+1

Except, https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker does include a compatibility table which seems adequately complete (all noticeable browsers support it and have since Chrome 1, FF 4, Opera 9, Safari 3, even IE 9).  So maybe not needed in this table.

**Comment by jeremy21212121** [comment]
> +1
> 
> Except, https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker does include a compatibility table which seems adequately complete (all noticeable browsers support it and have since Chrome 1, FF 4, Opera 9, Safari 3, even IE 9). So maybe not needed in this table.

At first glance, the support for TreeWalker looks to be pretty much across the board on MDN. But if you dig in a bit, support is kind of weird and mixed. For example, [document.createTreeWalker](https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker) has unknown support for Edge for setting `whatToShow`, which filters which nodes are returned when, for example, `TreeWalker.nextNode()` is called.

Edge 12 has full support for [TreeWalker.whatToShow](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker/whatToShow), which is read only. So presumably it would have to support setting `whatToShow`, otherwise what is the point of reading it? But who knows, this is Edge we are talking about.

Personally, I would like to see TreeWalker added to caniuse, as I prefer the UI to that of MDN for checking browser compatibility. That said, I do understand that caniuse doesn't aspire to have every browser API, but instead focus on the ones that have mixed support. To be able to make a case for TreeWalker, one should probably first establish Edge's support for setting `whatToShow` with  `document.createTreeWalker()`.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_treewalker
