### ISSUE TITLE
Add support for text-decoration-skip-ink

### ISSUE THREAD

**Issue by ghost** [Fyrd/caniuse#3979]
The text-decoration-skip-ink CSS property specifies how overlines and underlines are drawn when they pass over glyph ascenders and descenders.

Using this feature allows to drastically improve text readability for dyslexic users with skip-ink underlines.

**Comment by Ugoku** [comment]
[MDN page](https://developer.mozilla.org/nl/docs/Web/CSS/text-decoration-skip) , though support data for Chrome is wrong there. This is supported starting in [Chrome 64](https://www.chromestatus.com/feature/5631679087509504)

**Comment by jensimmons** [comment]
I believe we should add this as a separate page to Can I Use. Some of this information is sort of included in the broader page for `text-decoration`, but there so much that fall under text-decoration, and much of that spec is still in flux, or is not going to be supported by browsers soon. 

Meanwhile, `text-decoration-skip` is much better supported, and a clearer tool for web designers/developers. Having a Can I Use page will help clarify.

**Comment by Schweinepriester** [comment]
+1

<https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/70>

> [css-text-decor-4] Implement text-decoration-skip-ink. [bug 1411922](https://bugzilla.mozilla.org/show_bug.cgi?id=1411922 "FIXED: [css-text-decor-4] Implement text-decoration-skip-ink")

**Comment by jensimmons** [comment]
We really do need a page for this. 

I started researching the details of exactly what's going on, and made a test to help me figure it out... https://codepen.io/jensimmons/pen/BaBzQRz?editors=1100

**Comment by jensimmons** [comment]
This is actually the MDN page for this property: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink The one linked to above is for `text-decoration-skip`, which is a longer-hand property, and is _not_ the same thing as `text-decoration-skip-ink`.

To be extra clear, there are three levels of longhand/shorthand here...
- `text-decoration`
- `text-decoration-skip`
- `text-decoration-skip-ink`

`text-decoration` has been around forever. `text-decoration: none` removes all underlines.

`text-decoration-skip-ink` is a newer feature that makes browsers skip over descenders in type (like the 'g') when drawing an underline. It looks nicer, more polished. Originally the web did draw underlines through descenders. As browsers implement `text-decoration-skip-ink`, they are switching the default from `none` to yes do this. (A very unusual thing in new CSS, to change the default behavior of something on the web.)

`text-decoration-skip-ink: none;` tells the browser to not draw underlines while skipping-ink, meaning go ahead and cross through the descenders. Don't skip them. Sometimes you don't want ink skipping to happen. And this gives Authors control over things. It works in Chrome 64+, Firefox 70+, presumably Edge when it switches to Chromium... more compat data at https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink#Browser_Compatibility

`text-decoration-skip` is a work-in-progress. It's intended to add more features to control the drawing of underlines, sidelines, overlines, and other things that are done with `text-decoration`... especially for non-Latin scripts, where typography is different than it is when using the Latin alphabet. No one has fully implemented the parts of `text-decoration-skip` that are not `text-decoration-skip-ink` yet, because, well "fully" isn't even defined yet. Safari has partial support for some of it... but I don't think it's worth documenting or teaching about yet, because it's too early. It might not even happen, or might happen far into the future. There's work to be done in the CSSWG. 

Meanwhile, it's the right thing for Chrome and Firefox to have implemented `text-decoration-skip-ink` without implementing any support for `ink` in `text-decoration-skip`. What's hard for web developers is that Webkit did not implement `text-decoration-skip-ink`, leaving web developers stuck, forced to either ignore Safari, or to use `text-decoration-skip: none` as a risky substitute for `text-decoration-skip-ink: none`. 

Perhaps the note on `text-decoration-skip-ink` for Safari could say "partial support" — that you can get to this feature in Safari by using `text-decoration-skip: none;` (which will cause it to skip ink), but that doing so is risky, because it might have unintended consequences for the future (when more features are added to `text-decoration-skip` besides `text-decoration-skip-ink`).

**Comment by jensimmons** [comment]
I made a much simpler test of text-decoration-skip-ink:
https://codepen.io/jensimmons/pen/VwZjmGY?editors=1100

**Comment by Schweinepriester** [comment]
<https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75>

> The `all` value for the [`text-decoration-skip-ink`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink "The text-decoration-skip-ink CSS property specifies how overlines and underlines are drawn when they pass over glyph ascenders and descenders.") property has been added ([bug 1611965](https://bugzilla.mozilla.org/show_bug.cgi?id=1611965))

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_text-decoration-skip-ink
