### ISSUE TITLE
Position: sticky;  Works in Chrome 62

### ISSUE THREAD

**Issue by BenjaminHoegh** [Fyrd/caniuse#4047]
Google Chrome Version 62 (Officiel version) (64-bit)

`div` works with `position: sticky;`

[Demo](https://ebidel.github.io/demos/sticky-position-event.html)

**Comment by Fyrd** [comment]
Yes, on the site it's marked as partially supported only due to lack of support or table header elements. That it works on `div`s is implied. May I ask how it appeared otherwise to you?

**Comment by SelenIT** [comment]
It seems that Edge 16 also doesn't support `position: sticky` for table rows and table headers, despite being marked as fully supporting it ([my testcase](https://codepen.io/anon/pen/VyzOoW)).

Also, Chrome [has nearly fixed this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=702927#c16) for version 64 or 65, but ran into some real-world compatibility problems, so they rolled back the fix for now.

**Comment by Fyrd** [comment]
Closing this issue as I believe https://caniuse.com/#feat=css-sticky covers the info appropriately.
