### ISSUE TITLE
Add KaiOS/Jio Phone to caniuse data

### ISSUE THREAD

**Issue by IamManchanda** [Fyrd/caniuse#4059]
I can only tell you that this is a big user base that needs to get tracked 

Related links:
https://github.com/Fyrd/caniuse/issues/3904#issuecomment-350544237
https://twitter.com/KaiOStech/status/960759103382470656

**Comment by IamManchanda** [comment]
Hey bro if you check this https://www.kaiostech.com/mwc-2018-kai-announces-partnerships-with-mobile-industry-giants/

I think this is really needed @Fyrd 

You can contact them if you need some data

Only thing I can tell is that this operating system have large user base in India ... I mean Billions! Thank you :)

**Comment by IamManchanda** [comment]
Hey @Fyrd ... Awaiting your response

**Comment by Fyrd** [comment]
I'm in the process of adding a new method for adding new browsers that are based on existing browsers, I'd like that in place before I add KaiOS. FYI, KaiOS has about 1.34% usage share in India according to StatCounter:
http://gs.statcounter.com/browser-market-share/all/india/#monthly-201803-201803-bar

So that's significant, but not too huge.

**Comment by IamManchanda** [comment]
@Fyrd Means some data issue of about 10% still ... hmmn... Interesting!

**Comment by quickstreamingmedia** [comment]
https://github.com/blazeinmedia/airtelandjiolinks

**Comment by sombriks** [comment]
Indeed. Please add KaiOS, those modern javascript based feature phones will enter in the big picture soon, also make apps are dead easy and the hardware is everything but expensive!

**Comment by Fyrd** [comment]
KaiOS Browser has now been added!
