### ISSUE TITLE
Why is there no css box-pack attribute?  Or is Non-standard attribute not displayed?

### ISSUE THREAD

**Issue by heicks** [Fyrd/caniuse#4162]
https://developer.mozilla.org/en-US/docs/Web/CSS/box-pack

![image](https://user-images.githubusercontent.com/12287943/38227864-e16ea7dc-3732-11e8-8c08-b701964c8715.png)

------------
I haven't heard of this box-pack css before. So I searched at caniuse.com, but I didn't find it. I went to google search and suggested that Non-standard was replaced. Why?

**Comment by Fyrd** [comment]
If your question is "why was it replaced", basically the flexbox specification went through various revisions and `box-pack` is just the name of the property that I believe is now `justify-content`.

You can find some information on the history of flexbox at http://annairish.github.io/historicizing/history though you're pretty safe just focusing on the latest version and its properties, since they're supported by all modern browsers.

**Comment by Fyrd** [comment]
Now available via MDN BCD data: https://caniuse.com/mdn-css_properties_box-pack
