### ISSUE TITLE
/deep/ combinator

### ISSUE THREAD

**Issue by oswee** [Fyrd/caniuse#4174]
From Shadow DOM spec.

**Comment by cvrebert** [comment]
This was subsequently renamed to `>>>` and will probably be removed from the spec:
https://github.com/w3c/csswg-drafts/issues/640

The [intent discussion](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/HX5Y8Ykr5Ns/discussion) from https://www.chromestatus.com/feature/4964279606312960 suggests it's Chrome-only, and since Chrome 63 was changed to be just an alias of the regular descendant combinator.

**Comment by cvrebert** [comment]
Removed from the spec: https://github.com/w3c/csswg-drafts/pull/2511
