### ISSUE TITLE
AudioWorklet

### ISSUE THREAD

**Issue by ArnaudBienner** [Fyrd/caniuse#4178]
WebAudio API has been updated to add AudioWorklet [1], to replace (deprecated) ScriptProcessor API.
This will allow to run custom JS code directly within the audio thread, instead of the main thread, preventing glitch and other issues which can arise when audio processing isn't real time.
Chrome shipped this feature [2].

canise already have a page for WebAudio API, but since this sounds like a major feature to me, I believe it would be nice to have a dedicated page for AudioWorklet.
Or do you think this having a note on the current WebAudio API page will be enough?

[1]: https://webaudio.github.io/web-audio-api/#audioworklet
[2]: https://developers.google.com/web/updates/2017/12/audio-worklet

**Comment by ArnaudBienner** [comment]
I'm fine to do a pull request for this, but wanted to know first if it was worth it.

**Comment by nchase** [comment]
Regardless of implementation (a note on the current WebAudio page or a separate page), it would be great if I could type 'AudioWorklet' on caniuse and see this information, wherever it happens to live.

**Comment by BillyWM** [comment]
This is pretty major in my opinion. Web Audio has been waiting for Audio Worklet to finally be ready for years now (I've been following Web Audio developments since ~2011). ScriptProcessorNode was officially deprecated in 2014 without this replacement actually being ready until recently.

**Comment by cristiano-belloni** [comment]
Any news on this?

**Comment by simon-robertson** [comment]
I have just searched caniuse.com and was expecting a search for [audio worklet](https://caniuse.com/#search=audio%20worklet) to return supported browser versions, but no results were returned. It has been [available in Chrome](https://developers.google.com/web/updates/2017/12/audio-worklet) since version 64.

This is one of those features that should, IMHO, have its own table because Web Audio support doesn't necessarily mean Audio Worklet support. The same is true for WebGL and WebGL2, but those have separate compatibility tables.

**Comment by tommyrice** [comment]
+1

**Comment by kross-italk** [comment]
It seems firefox has similar problems. "Compatibility unknown"
> https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet

**Comment by Fyrd** [comment]
Update the MDN data recently, https://caniuse.com/#feat=mdn-api_audioworklet & related now cover this feature.
