### ISSUE TITLE
Edge 17 doesn't support CSS Backdrop Filter without prefix

### ISSUE THREAD

**Issue by Studio384** [Fyrd/caniuse#4212]
Currently, Can I Use is showing Edge 17 (and 18) as supporting CSS Backdrop Filter entirely, but the ```-webkit-```-prefix is required for it to work and thus it isn't fully supported yet.

**Comment by BenjaminHoegh** [comment]
Are you sure about that? All I can see is that the support the default one on [developer.microsoft.com](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/17063/?compareWith=16299)

but then again maybe -WebKit- is the default for it, as Apple was one of the big leaders to get this feature integrated as a standard at W3C

**Comment by Studio384** [comment]
I'm sure, I've tested it out. In the screenshot below you can see that Edge 17.17134 doesn't even recognize ```backdrop-filter``` as a valid property and instead does recognize ```-webkit-backdrop-filter```.

<img width="248" alt="capture" src="https://user-images.githubusercontent.com/1693592/39087600-9c92e752-45a3-11e8-966a-4051c3c2cfaa.PNG">

**Comment by dstorey** [comment]
I think this is the case. I'll check why we did this. If other browsers support without a prefix then we really should do that too.

**Comment by Studio384** [comment]
Given that Safari is the only browser beyond Edge to currently support this, it is kinda weird to use the prefixed version here. Yes, Safari uses the prefix version as well, but... well... it's only Safari. Chrome's experimental implementation doesn't support ```-webkit-backdrop-filter``` either, only ```backdrop-filter```.

**Comment by Studio384** [comment]
Ref: MicrosoftEdge/Status#595

**Comment by dstorey** [comment]
I checked and it was intentionally added with just the Webkit prefix for now until we know the spec is stable and won't change. We will unprefix it when other browsers are ready to enable by default and ship unprefixed.

**Comment by Studio384** [comment]
So why use the -webkit- prefix for this anyways? Why not just the -ms- prefix?

**Comment by dstorey** [comment]
because existing content uses -webkit- and not -ms-

**Comment by Studio384** [comment]
Not for this particular thing, and someone else doing it doesn't make it a good argument (if I jump from a bridge, would you too?).

**Comment by dstorey** [comment]
It is an argument as devs would tend to not use the ms or moz or o prefix and thus other non webkit browsers wouldn't get the correct experience. This has been a problem for over a decade since before I worked at Opera. That is exactly the reason why there is a [WHATWG Compat](https://compat.spec.whatwg.org) spec.

There will be very few if any new ms prefixes going forward as the new way is to use feature flags or origin trials until a feature is stable and browsers can release unprefixed. But this feature predates this with Safari releasing a webkit prefixed version. This has also been an in demand feature to enable things like the acrylic material in Fluent design system. Once it is unprefixed the webkit prefix version will likely live along side it for a while, like other webkit prefixed properties.

**Comment by Fyrd** [comment]
Have added a note on this.
