### ISSUE TITLE
What browsers do baidu 7.12 and and_qq 1.2 refer to?

### ISSUE THREAD

**Issue by ylemkimon** [Fyrd/caniuse#4463]
### Baidu 7.12

According to [a user-agent string database](https://www.myip.ms/view/comp_browsers/9127/Baidu_Browser_7_12.html), Baidu Browser 7.12 doesn't seem to be a separate browser, but an Android WebView wrapper (notice the `wv` in user-agent string):

> Mozilla/5.0 (Linux; Android 7.0; VIE-AL10 Build/HUAWEIVIE-AL10; **wv**) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.116 Mobile Safari/537.36 baidubrowser/7.12.12.0 (Baidu; P1 7.0)

There is DU Browser (DU is a brand name for Baidu) in Google Play, whose current version is 6.4.0.4, which is less than 7.12, and its user-agent string contains `bdbrowser`, not `baidubrowser`.

### QQ Browser for Android 1.2

The user-agent string of QQ Browser seem to be containing `QQBrowser`, but Google exact search of `QQBrowser/1.2` shows no browser for Android. Only one it shows is for OS X.

There is [an APK file](https://www.apksum.com/app/qq-browser/com.tencent.mtt.intl) for QQ Browser 1.2, but I can't seem to run it on any Android versions. It force closes on every Android version when loading a page.

There is QQ Browser in Google Play, but its version is 8.7.0.4340, which is probably a way newer than 1.2.

**Comment by Fyrd** [comment]
My information on each browser is a bit limited, but I was asked to include them by Google representatives who have contacts with these browser vendors. 

What I know is that both are mobile (Android) browsers with high usage share in China.  They are both customized versions of Chromium, not just webviews mapping to a specific version of Chromium. Neither is available on Google Play because Google Play is not allowed in China. If you like I can look up the URLs on where you can get them, though it may not be the most secure thing to do.

Let me know if you'd like any more details and I'll see what I can find out.

**Comment by ylemkimon** [comment]
@Fyrd Thank you for the reply!

Could you let me know where (URL) I can get them? (Testing will be conducted on sandboxed environment, so no worries.)

**Comment by Fyrd** [comment]
@ylemkimon Sorry forgot to respond to this. Here's the links:
UC Browser:
http://sj.qq.com/myapp/detail.htm?apkName=com.UCMobile

QQ Browser: 
http://sj.qq.com/myapp/detail.htm?apkName=com.tencent.mtt

Baidu Browser:
http://sj.qq.com/myapp/detail.htm?apkName=com.baidu.browser.apps

**Comment by ylemkimon** [comment]
@Fyrd Thank you for the links. This solves the question for the Baidu browser. However, the version number of QQ Browser on links you gave is 8.8, which seems way older than 1.2.

**Comment by Kristinita** [comment]
+1. [**9.0.2.4800 — is latest QQ Browser version**](https://sj.qq.com/myapp/detail.htm?apkName=com.tencent.mtt) for February 2019. Can I use need updates.

Thanks.

**Comment by Fyrd** [comment]
Questions have been answered and QQ Browser was recently updated, so closing this issue.
