### ISSUE TITLE
AV1 codec might be supported by Chrome Android 70

### ISSUE THREAD

**Issue by tuxayo** [Fyrd/caniuse#4626]
https://www.androidpolice.com/2018/10/17/chrome-70-adds-av1-video-support-improves-pwas-windows-apk-download/

> Starting with Chrome 70, AV1 support is now enabled by default on desktop platforms and Android.

Can someone with Chrome Android check? Or find a more more authoritative source?

- https://www.youtube.com/testtube
- Always Prefer AV1
- https://www.youtube.com/watch?v=2nXYbGmF3_Q&t=0s&index=2&list=PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS
- request desktop site
- right click => Stats for nerd
  - is there a way to do this on mobile?
- read what's written in "Codecs"

**Comment by Fyrd** [comment]
Doesn't seem to pass my tests (that do pass in Chrome/Mac) so I'm gonna say no. If someone can provide otherwise please share.

**Comment by tuxayo** [comment]
Thanks for trying :)

What is your test? That might help others. As mine isn't really suitable for mobile.

**Comment by DeeDeeG** [comment]
This is still not supported in Chrome for Android as far as I can tell.

I looked for any flags in `chrome://flags` and there was no AV1 flag on Chrome for Android. (That indicates to me there may be no feature to turn on or off. It's just not there at all.)

Since it might just be enabled, no flag, I then went to the Bitmovin AV1 demo: http://bitmovin.com/demos/av1 and that didn't work.

Then I went to https://youtube.com/testtube (which just shows the page for a YouTube account/channel named "testtube" on mobile browsers, so I hit the hamburger menu and selected "Request Desktop Site") and I believe that page also said " AV1 decoding is not available on this browser yet."

I tried this with Firefox for Android also, and you can enable AV1 there in `about:config` (The flag to toggle is `media.av1.enabled`).

But every time I tried to play an AV1 video on YouTube (e.g. "New Rules music video by Dua Lipa supports AV1 if you enable AV1 on YouTube at https://youtube.com/testtube...) or the Bitmovin demo... Firefox for Android crashed. So I think AV1 support needs some updates and bug fixing in Firefox for Android, but the feature is technically present.

**Comment by csagan5** [comment]
Can you guys please test with [Bromite](https://www.bromite.org]? It is a fork of Chromium, it works with the AV1 tests I could run from here: https://tools.woolyss.com/html5-audio-video-tester/

(disclaimer: main Bromite author here)

What I did for this feature was basically enable it internally (and forcefully for Android), although I am afraid querying the support via Javascript is not yet correct.

**Comment by tuxayo** [comment]
> Firefox for Android crashed

Same here, didn't took the time to get a logcat and search if the issue is known.

**Comment by DeeDeeG** [comment]
@csagan5, my Android phone is borrowed and I can't side-load any apps on it. So I can't test Bromite. But it seems like the tests you mentioned running over in #4699 show that it works!

---

@tuxayo, it doesn't crash in Firefox Nightly for Android, so they must have done something to fix it?

**Comment by csagan5** [comment]
> @csagan5, my Android phone is borrowed and I can't side-load any apps on it. So I can't test Bromite. But it seems like the tests you mentioned running over in #4699 show that it works!

It's fine, I would not expect it to be included in the list of browsers anyways (small user base); you can also use the Android Emulator to run these type of tests.

**Comment by Kagami** [comment]
>Firefox for Android crashed

Enable `media.av1.use-dav1d`

**Comment by Kagami** [comment]
@csagan5 just tested my avif.js demo in Bromite and it works fine. Normal AV1 mp4 files of course work too. Nice!
