### ISSUE TITLE
"Become a Patron" button returns a 404 error

### ISSUE THREAD

**Issue by mdawar** [Fyrd/caniuse#4780]
I just wanted to let you know that the "Become a Patron" button is sending the users to a 404 page on patreon.com.

**Comment by DeeDeeG** [comment]
from visiting the [patreon page](https://www.patreon.com/caniuse) and inspecting the "BECOME A PATRON" button, this seems to be a working URL: https://www.patreon.com/join/caniuse?

_(Not sure why they add a question mark, since there's no parameters after it. It works okay without the "?" as well, i.e. https://www.patreon.com/join/caniuse)_

**Comment by Fyrd** [comment]
Thanks for reporting this, has now been fixed! (and thanks for the URL @DeeDeeG )
