### ISSUE TITLE
Q: What defines 'partial support' ?

### ISSUE THREAD

**Issue by rejas** [Fyrd/caniuse#5119]
Got this ticket here https://github.com/Modernizr/Modernizr/issues/2476
and was wondering how caniuse defines "partial support" ? 
If an implementation has a bug or when it only supports a part of a feature?

**Comment by Fyrd** [comment]
It's kind of context dependent and can be either of those two, though the bug has to be pretty serious to be "partial" support. Basically if the feature can be used just fine in some cases but not in other fairly common cases, then it's partial support.

In the case of sticky headers, I think because it's a fairly common use case to want to use sticky on table headers it seems worth considering partial support.
