### ISSUE TITLE
No JSON data exposed for features from MDN browser-compat-data

### ISSUE THREAD

**Issue by sideshowbarker** [Fyrd/caniuse#5187]
#### Problem
When I browse to https://caniuse.com/#feat=mdn-api_abstractrange, the Can I Use web UI gives me a human-readable view of information about browser support for the AbstractRange API — a feature for which the support data comes from the MDN browser-compat-data repository — but as far as I can see, that information isn’t exposed as JSON data (that is, not in the same way as features for which the data is maintained directly in the https://github.com/Fyrd/caniuse repo itself).

This is a general issue for any features whose support data comes from the MDN browser-compat-data repository (not just for the AbstractRange API, which I’m just citing as an example). And the specific problem is causes is: it prevents downstream consumers of Can I Use data from having a consistent means for accessing the same complete set of data from which Can I Use builds its own web UI.

#### Example of a specific problem with a downstream consumer
Bikeshed is a tool used for many specs — including most or all of the CSS specs, and dozens of other W3C specs, and all but one of the WHATWG specs (the HTML spec is the only WHATWG spec not built using Bikeshed) — and it has a feature to inject annotations into generated specs based on Can I Use data, as documented at https://tabatkins.github.io/bikeshed/#metadata-include-can-i-use-panels.

But if I try using that Bikeshed feature with the DOM spec, by adding a `canise=mdn-api_abstractrange` attribute to the source for the https://dom.spec.whatwg.org/#interface-abstractrange *Interface AbstractRange* section, I get an *Unrecognized Can I Use feature ID: mdn-api_abstractrange* error.

So, I’d like to be able to use `canise=mdn-api_abstractrange` with Bikeshed — and in general, be able to do the same for any `mdn-`-prefixed Can I Use feature IDs — and have it “just work”.

#### Possible solution
I can imagine it being possible that, at the time the build is run to generate/update the Can I Use web UI, the build backend can:
1. Take whatever in-memory data is being using to generate the web content for features which come the from the MDN browser-compat-data repository (the `mdn-`-prefixed features).
2. Serialize that data out as JSON.
3. Write that data to a clone of the https://github.com/Fyrd/caniuse/tree/master/features-json directory, as per-feature JSON files in the same JSON format as the existing files there.
4. Commit the added/updated files to git and push to https://github.com/Fyrd/caniuse.
5. Repeat that process each time to Can I Use web UI is re-built/re-published.

I recognize that solution introduces redundancy — in that it’d mean data about the same features would now be under version control both in the MDN browser-compat-data repo and the Can I Use repo, and the currency of the Can I Use data would lag somewhat behind MDN browser-compat-data — but I think that’s OK because it’d give Can I Use data consumers (e.g., Bikeshed) the significant value of consistent programmatic access to data for all the same features exposed in the Can I Use web UI, regardless of whether the data is ultimately sourced from Can I Use itself or from MDN browser-compat-data.

**Comment by Fyrd** [comment]
Yeah, I can see how following those steps would definitely make sense from the Bikeshed point of view, possibly other downstream consumers as well. However, I'd instead make the argument that the annotations used on W3C/WHATWG specs would be better off using the MDN browser compat data instead.

Reasons being:
- MDN BCD has a much larger feature coverage than caniuse, and is much more granular. Seems in particular better suited for specifications.
- MDN BCD is essentially better organized and I suspect will be more reliable over time, as it's 
governed and managed by an organization rather than an individual relying heavily on contributors for data updates.

Worth pointing out that there's a number of projects (of which caniuse is one) that consume the MDN data, as listed [here](https://github.com/mdn/browser-compat-data#projects-using-the-data), so they're definitely expecting to be used beyond the MDN docs pages. 

I'd also push back against adding the data to the caniuse repo since it's currently included in some projects as an NPM module and is already quite sizable. Adding MDN BCD would increase the size roughly 21x, which not all consumers would appreciate.

I get that the additional work of adding another data source isn't very appealing, but I'd think it would be of benefit in the long run.

**Comment by sideshowbarker** [comment]
> I'd instead make the argument that the annotations used on W3C/WHATWG specs would be better off using the MDN browser compat data instead.

Yeah, I am inclined to agree. For spec purposes, we already have some tool support for generating annotations from the MDN browser compat data — in the Respec tool and in the Wattsi tool we use for building the HTML spec. So Bikeshed is the only spec-build tool＊ we have that still lacks MDN-annotation support, and we have https://github.com/tabatkins/bikeshed/issues/1372 open for adding that support. But that issue’s been open for a year now without anybody stepping forward to work on it… So I guess I just need to bite the bullet and make time to work on it myself.

Given all that, I’ll take the liberty of closing this.

_＊ As far as spec-build tools lacking MDN-annotation support, it would also be nice to have that support in the https://github.com/bterlson/ecmarkup tool that used for building the ECMAScript spec…_

**Comment by Fyrd** [comment]
Ah, excellent. Glad that option works for you!
