### ISSUE TITLE
Remove closed issues from the feature suggestion list

### ISSUE THREAD

**Issue by antonjuulnaber** [Fyrd/caniuse#5253]
It seems like the [feature suggestion list](https://caniuse.com/issue-list) hasn't been updated in a while, and is linking to a lot of features that have already been implemented. That makes the list very frustrating to use.

Here's a list of closed issues that I randomly found, without making any specific effort to find them:

`#1` CSS3 overflow-x and overflow-y #1665 
`#5` `<keygen>` tag #1155 
`#7` document.readyState #1274
`#19` `<audio>` onended event #1033 
`#56` CSS's `@import` #1411 

It would be great if the list could be updated.

**Comment by Fyrd** [comment]
Yeah, I've been thinking of retiring that page in favor of the [GitHub reaction count](https://github.com/fyrd/caniuse/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3A%22Support+data+suggestion%22) list which accomplishes what the suggestion list was originally for. Thanks for that list though, will close those issues.

**Comment by antonjuulnaber** [comment]
Arh, that makes sense. I will just use GitHub going forward then.
But yeah, definetely make it clear on the site that people should use GitHub instead :)

**Comment by saeidshoar** [comment]
Hi Unfortunately, despite the many attempts I have made on the internet for
4 years and in vain now that I am facing financial and economic problems so
far that my personal life has collapsed I have only a few hours left to pay
for my work online. Turn to cash because most digital currency sites in
Iran are filtered and I was completely frustrated with my wife and
children. Anyway thank you dear friend for taking the time to cooperate and
I wish you success and happiness. Thanks and God bless

‫‪Anton Juul-Naber‬‏ <‪notifications@github.com‬‏> در تاریخ یکشنبه ۲۶
ژانویهٔ ۲۰۲۰ ساعت ۱۲:۴۹ نوشت:‬
