### ISSUE TITLE
Difference theme-color Meta Tag between Edge and Chrome 79/80

### ISSUE THREAD

**Issue by TQxTim** [Fyrd/caniuse#5286]
![image](https://user-images.githubusercontent.com/43742253/74821734-56d51080-5304-11ea-8711-a0c867b9a15d.png)
How is this possible, if both use the same engines?

**Comment by atjn** [comment]
Chrome and Edge are free to customize Chromium however they'd like, so it is definetely possible for them to have feature disparity, especially when it relates to the UI, which is very clearly different from browser to browser.

With that said, it seems like Edge does support theme-color, so I will take look at it. Thanks for noticing!

**Comment by atjn** [comment]
Nope, sorry. Edge does not support the theme-color meta tag. It does however support the theme-color attribute in the web app manifest, which is why i was originally confused.

You can test this yourself by installing the [Google Developer webapp](https://developers.google.com) in both Chrome and Edge. Notice that the theme-color is currently set to white, because that is what is defined in the web app manifest.
Now navigate to [this page](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android) within the webapp. Chrome will change the toolbar to blue because it reads the theme-color meta tag on the page (which is set to blue), but Edge does not.

**Comment by Fyrd** [comment]
Closing this issue as per @atjn's comments
