### ISSUE TITLE
only latest and_chr is shown

### ISSUE THREAD

**Issue by connorjclark** [Fyrd/caniuse#5419]
on any page, but for example: https://caniuse.com/#feat=async-functions

![image](https://user-images.githubusercontent.com/4071474/81268610-06b14480-8ffd-11ea-8ec2-d75f65cbc7c4.png)

![image](https://user-images.githubusercontent.com/4071474/81268628-0ca72580-8ffd-11ea-92aa-4c452d6150bb.png)

My expectation is that it'd show all the versions that supported this feature, just like the other browsers.

Is this expected? Maybe because it'd mostly be a duplicate of Chrome?

**Comment by Schweinepriester** [comment]
Afaik @Fyrd only keeps the latest version for and_chr:
https://github.com/Fyrd/caniuse/blob/master/features-json/async-functions.json#L346
(compare Chrome: https://github.com/Fyrd/caniuse/blob/master/features-json/async-functions.json#L125)

I believe the reasoning is indeed because of the similarities to Chrome versus overhead when maintaining the data.

However, past and future versions of and_chr have been requested:
- Past: #3518
- Future: #2926

And while digging those up, Fyrd has stated a bit more on the matter in the "past" issue, probably the better reply than my ramblings: https://github.com/Fyrd/caniuse/issues/3518#issuecomment-308931205

**Comment by connorjclark** [comment]
thanks for the context @Schweinepriester! I'll go ahead and close this as I'm not adding any additional information than the existing issues.
