### ISSUE TITLE
CSS API vh - broken link?

### ISSUE THREAD

**Issue by jkjustjoshing** [Fyrd/caniuse#5496]
https://caniuse.com/#feat=mdn-api_css_vh

I was curious what the difference between CSS `vh` units and the `vh` "CSS API" was. I clicked on the "MDN Web Docs" link at the bottom, which points to this broken link - https://developer.mozilla.org/docs/Web/API/CSS/vh

Either fix this link, or remove this entry if it doesn't apply anymore (couldn't find reference to it on the MDN docs).

**Comment by Fyrd** [comment]
Thanks for reporting! This table is generated from the MDN browser-compat-data repo which includes links to related MDN articles that may have not (yet) been created.

Since this hasn't been the first report on the issue I've gone ahead and added some link-checking to these links when updating the MDN BCD data to remove the links that don't exist yet. I'm happy to report that that means the link for this feature has been automatically removed, so closing the issue.
