### ISSUE TITLE
HTML Symbols/Entity

### ISSUE THREAD

**Issue by FrankSalmick** [Fyrd/caniuse#5503]
[HTML entities](https://www.w3schools.com/charsets/ref_html_entities_h.asp#:~:text=Chrome%20and%20Opera%20have%20good,35%2B%20support%20all%20the%20entities.) - I am not aware of their browser support but I have observed all the ones I tried working in most modern browsers (edge/chrome/ff). I don't have an apple device to test with Safari.

There are also some additional ones [here](https://www.toptal.com/designers/htmlarrows/)

**Comment by Fyrd** [comment]
I believe HTML entities have been supported since browsers back in the 90s as part of the early versions of HTML. The exact characters that are supported depends on things like font and system support, not browsers.
I think it's also more commonplace these days to just use a character directly rather than its HTML entity which should work fine as long as the encoding's set to UTF-8.
