### ISSUE TITLE
Add Opera Mobile 59

### ISSUE THREAD

**Issue by twifkak** [Fyrd/caniuse#5602]
It appears the newest version of Opera Mobile is 59. This corresponds to Chromium M83, so it should include support for many more features than the existing entry for Opera Mobile 46 from 2 years ago. Is it worth adding an entry for this new version?

**Comment by Fyrd** [comment]
Yup, will get on adding this one shortly. Thanks for pointing it out!

**Comment by Fyrd** [comment]
Done!

**Comment by mlnor27** [comment]
@Fyrd  Hi! I wanted to follow up on this topic even though the issue has been closed for a while now.

I'm a bit confused on why the 46th version of Opera Mobile has been dropped and how you made the choice to directly jump to the 59th version. What about [all the versions](https://opera-browser.en.uptodown.com/android/versions) in between? Is it because they are equivalent?
I've stumbled upon an old reply of yours in #3518 , I don't know if it applies for this case.
Right now, looking at https://caniuse.com/ciu/comparison, we can only see 3 different versions for Opera Mobile. 

By the way, It's also a bit confusing when we look at the way Opera names their mobile versions now. It looks like they simply name them Opera. I'm not really sure since when, but it kinda gives the impression that mobile and desktop versions have been aligned.. But that's a different topic.
   
I'm also writting you as it has repercussions on third party tools depending on [`browserslist`](https://github.com/browserslist/browserslist), with which I've recently encountered errors linking to Opera Mobile 46 being unknown.

I'd greatly appreciate knowing the reasoning behind this versions jump.
Thank you!

**Comment by Fyrd** [comment]
@mlnor27 The reply you linked to does indeed largely explain it, like for other Android browsers I only track the latest version as that's the one easiest to test for. So when I get around to updating it the version will update to the latest one.

As Opera for Android is largely the same as Chrome for Android (engine-wise) I would probably just only include the latter in browserslist. Is there a particular difference between the browsers that require you to specify it?

**Comment by mlnor27** [comment]
> The reply you linked to does indeed largely explain it, like for other Android browsers I only track the latest version as that's the one easiest to test for. So when I get around to updating it the version will update to the latest one.

Alright, that's fair enough 👍🏼 

> As Opera for Android is largely the same as Chrome for Android (engine-wise) I would probably just only include the latter in browserslist. Is there a particular difference between the browsers that require you to specify it?

This is something that I'm trying to figure out, but based on the fact that Opera is chromium based, then as you said, they shouldn't be majorly diverging.

Thanks for the clarification!

**Comment by krystian3w** [comment]
https://github.com/CSS4-Selectors/website/pull/9

**Comment by Bobain95** [comment]
> @mlnor27 The reply you linked to does indeed largely explain it, like for other Android browsers I only track the latest version as that's the one easiest to test for. So when I get around to updating it the version will update to the latest one.
> 
> As Opera for Android is largely the same as Chrome for Android (engine-wise) I would probably just only include the latter in browserslist. Is there a particular difference between the browsers that require you to specify it?

**Comment by Bobain95** [comment]
Ermm
