### ISSUE TITLE
hyphens: auto does not work in Edge 88

### ISSUE THREAD

**Issue by fritzmg** [Fyrd/caniuse#5792]
Currently https://caniuse.com/?search=hyphen shows that `hyphens: auto` has full support in Microsoft Edge 88. However it is actually not supported at all - at least under Windows - not even with any of the prefixes (`-ms-` or `-webkit-`). Previous (non Chromium) versions of Edge _did_ support `hyphens: auto` with the `-ms-` specific prefix, as is indicated correctly on caniuse.

Since it does work in Chrome under Windows however, I suspect that this is more of a bug or oversight on Microsoft's part?

**Comment by Schweinepriester** [comment]
I've had a look - it trickled down from my change in #5656. I'm fairly certain that when a new version of Edge is added, the data is copied from the corresponding version of Chrome, so...

However, Note 1 doesn't seem to be accurate anymore as well, since Edge on macOS aces the tests using <https://tests.caniuse.com/css-hyphens>:

![image](https://user-images.githubusercontent.com/2644614/110025785-21913a00-7d30-11eb-834e-8610e2423208.png)

Currently updating my emulator to test Edge for Android.

I'll create a PR.

**Comment by vielhuber** [comment]
This still does not work in Edge 90, however https://caniuse.com/css-hyphens shows a green background on Edge 90. Please correct that.

**Comment by Schweinepriester** [comment]
I'll create another PR.
