### ISSUE TITLE
Add CSS "scroll-snap-type"

### ISSUE THREAD

**Issue by zbluebugz** [Fyrd/caniuse#5797]
CSS "scroll-snap-type" doesn't appear to be listed. It is supported by many browsers.

See: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type

**Comment by Schweinepriester** [comment]
[Searching](https://caniuse.com/?search=scroll-snap-type) leads to <https://caniuse.com/css-snappoints>, which [looking at the spec](https://www.w3.org/TR/css-scroll-snap-1/#scroll-snap-type), seems to cover `scroll-snap-type`. The feature on caniuse has it as a keyword to make is searchable: <https://github.com/Fyrd/caniuse/blob/main/features-json/css-snappoints.json#L439>
Related: #1673

Or am I missing something? :)

**Comment by zbluebugz** [comment]
On the snappoints page, scroll-snap-type is not mentioned anywhere.

Search results for scroll-snap-type-x and scroll-snap-type-y are listed and being listed as obsolete and unsupported by most browsers. This leads me to think that scroll-snap-type is not available/supported as it is not explicitly mentioned anywhere. However, it supported by most browsers.

**Comment by Fyrd** [comment]
I agree it is rather confusing the way it works now, largely due to https://caniuse.com/css-snappoints not explicitly mentioning all the properties that are included in the Scroll Snap Module and `scroll-snap-type-x` & `scroll-snap-type-y` being deprecated properties from an earlier version of the spec.

Furthermore, the caniuse feature is currently set to replace the MDN table for `scroll-snap-type` which is why it does not appear. Seems undoing that should fix this particular issue so I'll do that.

**Comment by Fyrd** [comment]
This was done, see https://caniuse.com/mdn-css_properties_scroll-snap-type so closing this issue.
