### ISSUE TITLE
The popups are too agressive

### ISSUE THREAD

**Issue by simevidas** [Fyrd/caniuse#5826]
When moving the mouse cursor over the support table, the popups are shown immediately. This is a problem because the user does not want to see the popup for cells for which the mouse cursor only moves over quickly.

I have recorded a video that shows the problem: https://www.youtube.com/watch?v=yghz-ximGG4

I think it would be better if the popup was only shown if the mouse cursor stayed over the cell for some minimum amount of time and/or the cursor stopped moving over the cell for a moment. That way, quickly moving the cursor over the table would not trigger any popups.

**Comment by boan-jfm** [comment]
Another issue is when you want to test it in browserstack, you can not hit the button before the popup has changed. Try to search for "flex", and hit the "Test on IE 10" almost impossible because the pop-up is so large - it changes when you hover over the other browser fields..

![image](https://user-images.githubusercontent.com/13201214/113833813-60c90580-978a-11eb-8468-0c61bbe5cea5.png)

**Comment by Fyrd** [comment]
There is now a brief delay before showing the popup, making it possibly to move the mouse over the table without triggering any popups.

@boan-jfm Yeah it was hard to find the right balance for those trying to reach the link and those trying to hover over an adjacent cell. To make it easier you you click the version cell first, that'll keep the popup from hiding and make it much easier to click the link.
