### ISSUE TITLE
Sort by Publication date

### ISSUE THREAD

**Issue by hyrious** [Fyrd/caniuse#6061]
The <q>Filter features</q> panel on the website is not working (specifically the <q>List sort</q> part), so I'm looking into the data to see if I can sort by myself. However I can not find a clue to do that.

Is it still possible to sort features by date? I mean other sort method can rely on `usage_perc_a` fields, but I see no field indicating the date.

**Comment by Fyrd** [comment]
Turns out the filtering and sorting logic had been broken for some time, just pushed some fixes for it. 

As for the publication date, to be clear it refers to the date the feature first appears on caniuse (when "shown" is set to true). So that should be the same as how it appears in the news as well as the "Publication date" order.

Also I need to document this somewhere on the site, but currently the filter only works on all caniuse features, not the ones from MDN. As such it doesn't filter search results, just all the entries in the database.
