### ISSUE TITLE
Drag and drop: Safari iOS 15

### ISSUE THREAD

**Issue by alexreardon** [Fyrd/caniuse#6080]
Right now HTML5 drag and drop is called out as not working on iOS Safari 15: https://caniuse.com/dragndrop

However, I tested on my own iOS device running Safari 15 and it does appear to be working

**Comment by Schweinepriester** [comment]
Where did you test? :)

**Comment by alexreardon** [comment]
https://tests.caniuse.com/?feat=dragndrop

On iOS 15 Safari

**Comment by Schweinepriester** [comment]
Ah, you responded while I was writing this comment - thanks! Checked as well, will create the PR now! Thanks! :)

---

Huh! Never mind, I was asking because <https://bestvpn.org/html5demos/drag/> was kinda wonky, but would you look at that:
<https://bugs.webkit.org/show_bug.cgi?id=223596>

<https://tests.caniuse.com/dragndrop> =>


https://user-images.githubusercontent.com/2644614/140818697-d1dd9751-87ad-4bd6-9767-f084dc5a61d7.MP4

![Screenshot 2021-11-08 at 22 03 12](https://user-images.githubusercontent.com/2644614/140818723-3ddbeb5d-aace-4ec5-b1a8-00ef786ba222.png)

**Comment by alexreardon** [comment]
According to https://bugs.webkit.org/show_bug.cgi?id=223596 the feature has now been implemented. The bug report calls out it was fixed in Safari 14; but I cannot test that. It looks like it was launched with iOS 15 to support it's new cross app drag and drop experiences

**Comment by alexreardon** [comment]
This HTML5 wrapper library is also working nicely on iOS 15 Safari: https://lukasoppermann.github.io/html5sortable/index.html

**Comment by alexreardon** [comment]
https://user-images.githubusercontent.com/2182637/140850865-7de8e103-84b5-4e56-a9a7-558e71944ac3.MOV
