### ISSUE TITLE
Firefox 95 for Android AVIF support

### ISSUE THREAD

**Issue by jonjensen** [Fyrd/caniuse#6133]
Hi. I wanted to note that AVIF is now enabled by default in Firefox 95 for Android, but it appears from CONTRIBUTING.md and my failing `npm run validate` that Firefox 95 for Android first needs to be added somewhere.

**Comment by Schweinepriester** [comment]
Yeah, Fyrd would need to change `and_ff` to `95`

https://github.com/Fyrd/caniuse/blob/f136c22cacb4edb9d808842198ba96a9c8bbad77/features-json/avif.json#L427-L428

there or really globally since for mobile browsers currently only one version is kept…

However, looking at desktop firefox one would think it would have been enabled by 93. Then again https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#av1_support_for_firefox_on_android 🤔

Were/are you able to test it's really enabled by default (in 95 or before)? 0:-)

**Comment by Fyrd** [comment]
Just updated Firefox for Android to 95 and updated the value for AVIF. Thanks!
