### ISSUE TITLE
"not a W3C Standard nor is it on the W3C Standards Track" features displayed on caniuse

### ISSUE THREAD

**Issue by dmitriid** [Fyrd/caniuse#6138]
As an example, caniuse displays [url=https://caniuse.com/import-maps]support status for Import Maps[/url]. However, even the oficial specification for them [states](https://wicg.github.io/import-maps/):

> This specification was published by the Web Platform Incubator Community Group. It is not a W3C Standard nor is it on the W3C Standards Track. 

There are undoubtedly many more such features where discussion and specification is still ongoing. However, caniuse is very much relied on to display the status of standardised/agreed on features, and inclusion of features that are experimental/in flux/implemented just a by a single browser engine ahead of time is potentially detrimental to the web.

**Comment by Fyrd** [comment]
It's often hard to know off-hand what the standardization status is of any given technology, so instead of excluding features entirely (which doesn't help anyone trying to find out more) the position caniuse takes is to inform developers of the current status in addition to showing the current support table.

Currently a feature like Import Maps has an "UNOFF" indicator next to its title to show it's an unofficial feature. If that seems insufficient we can add additional wording or when known share the position other browsers have on the technology ( https://mozilla.github.io/standards-positions/ for example is great for this ). Feel free to submit a pull request if you'd like for Import Maps to be more descriptive in this regard.

**Comment by dmitriid** [comment]
@Fyrd Ah. I completely missed the UNOFF label :) I could complain it's not prominent enough, but I won't :)

Thank you! This issue is now invalid.
