### ISSUE TITLE
Opera Mini usage data appears to be wrong

### ISSUE THREAD

**Issue by clshortfuse** [Fyrd/caniuse#6267]
Hi!

I was looking into the usage data and found it somewhat odd that Opera Mini still maintains the >1% usage, outpacing even IE11 today. I decided to look into the data and nothing I can find supports this. I downloaded the following from statscounter.com:

[Browser Versions April 2015 to April 2022 Worldwide Data](
https://gs.statcounter.com/chart.php?device=Desktop%20%26%20Mobile%20%26%20Tablet%20%26%20Console&device_hidden=desktop%2Bmobile%2Btablet%2Bconsole&multi-device=true&statType_hidden=browser_version&region_hidden=ww&granularity=monthly&statType=Browser%20Version&region=Worldwide&fromInt=201504&toInt=202204&fromMonthYear=2015-04&toMonthYear=2022-04&csv=1)

[Browser Versions by Country](https://gs.statcounter.com/download/browserversion-country/)

I converted the CSV and transposed them into the following Google Sheets document:

https://docs.google.com/spreadsheets/d/1DJnUh-MALpEjM52ot2CtVZr-j0SZxhFaGA4-SAfMaYk/edit?usp=sharing

I was a bit confused as to why some versions were missing. When I went far as back as 2015, I was able to see more versions, but still it was missing the newer version. So, I took it upon myself to install Opera Mini on my Android device and going to https://gs.statcounter.com/detect

* With Data Saver Off, the browser is detected as Opera 62.5
* With Data Saver Extreme, the browser is detected as Opera Mini 62.5

So, the reason why high number Opera Mini versions (eg: v20-v66) are basically nonexistent are because very few people on iOS and Android versions use it with Extreme saver on. 

The April 2022 stats for "Opera Mini" according to statcounter adds up to 0.12% which is a far cry from caniuse's 1.08%

On a related note, "Opera" usage for April 2022 adds up to 0.19% which is a lot lower than caniuse's ~1.3%

I haven't investigated the by region, and I will, but something is definitely off with the global stats.

Thanks for all you do! :)

**Comment by clshortfuse** [comment]
From their FAQ:

>BROWSERS: What browser versions do you track?
>To see the list of browser versions currently tracked, please select the "Browser Version" statistic and choose the "Bar" graph option. Next click "Download Data" - the downloaded file will list all browser versions currently tracked.

I was doing Line Graph, but with Bar graph, the numbers are still high.

With bar graph, it's 0.11% with both all versions or combined. In fact, with combined view, all of Opera Mini + Other add up to only 0.64%.

**Comment by andy-blum** [comment]
This is especially problematic when combined with @Fyrd's statements in #5118

> Regular Opera Mini however is not that popular a browser though and just uses the default OS browser engine

This implies that the `Opera Mini` category is _only_ there because it has its own rendering engine. This leads to the confusion that a browser with >1% global usage (and as high as almost 8% in Africa) does not even fully support features from ECMAScript 5.

On top of fixing the usage statistics, could the Opera Mini category have a clearer, more visible caveat that indicates it's only referring to the extreme-savings mode?

**Comment by Fyrd** [comment]
Happy to take a closer look at this, but I do believe the following are still true:
- Opera on mobile devices is still very popular (relatively speaking) in Africa ([StatCounter link](https://gs.statcounter.com/browser-market-share/mobile/africa/#monthly-202105-202205-bar))
- It's particularly popular because of the data savings options offered by the browser, suggesting many users are in fact using the extreme data savings mode. Some of this is mentioned in [this article](https://opera.gcs-web.com/news-releases/news-release-details/opera-bridging-digital-divide-sub-saharan-africa):

> [...] our small and powerful Opera Mini browser, with more than 500 million installations from Google Play, is among the most popular apps in the world because it provides users with up to 90% data savings - thanks to our unique data compression technology

If it holds true that many users still depend on this to affordably access the internet as mentioned in that article I want to make sure it's still represented on caniuse.

**Comment by clshortfuse** [comment]
@Fyrd I agree it's important we don't exclude users, but at the same time our data should be accurate to developers can make more informed decisions. The screenshot shared by @andy-blum shows Opera Mini usage as 7.74% where according to StatCounter, it's ~2% (as of April 2022). 

I can't get any math to conclude 7.74% for Africa. All Opera usage (Full + Mini) in Africa is 8.8%. Full versions of Opera is 6.68%. Opera Mini * is 2.0%. Even Other is only 0.98%. That means at best, Opera Mini in Africa is 2.98% (assuming every single "Other" device is a version of Opera Mini).

![image](https://user-images.githubusercontent.com/9271155/174101730-51c6947e-e990-4e93-b621-844a960c807e.png)

**Comment by Fyrd** [comment]
Some time last year I redid the usage data import which I believe has resulted in more accurate usage data for Opera Mini (currently 0.09% global, 1.34% in Africa). As such I'm closing this issue.

**Comment by julian-alarcon** [comment]
This should be reevaluated and Opera Mini should be removed.

It's is 2025 and Africa browser usage /internet conditions has changed a lot.
Opera Mini with Data Saver Extreme usage is lower now.

If the decision to keep it is still there because of usage, then even other less know browsers/browser engines should be in CanIUse.
