### ISSUE TITLE
For iOS, suggestion to stop favoriting Chrome with the "Safari & Chrome" name

### ISSUE THREAD

**Issue by nhoizey** [Fyrd/caniuse#6476]
It doesn't seem fair to only mention Chrome in addition to Safari, on iOS:

![image](https://user-images.githubusercontent.com/78213/192570110-94781790-0ffd-40d8-8325-7e7068e07149.png)

I could think of 3 "better" names:
- "Safari"
- "Safari & other browsers"
- "Safari & WKWebView"

**Comment by rik** [comment]
Another proposition: "All iOS browsers".

**Comment by aardrian** [comment]
All iOS browsers are still WebKit, yeah? So "WebKit (includes Safari, Chrome, Firefox)"...?

**Comment by nhoizey** [comment]
@rik @aardrian I think Safari and other browsers on iOS (using WKWebView) are a little different, but I don't know if there are differences in some features presented in Can I Use.

**Comment by rik** [comment]
> All iOS browsers are still WebKit, yeah? So "WebKit (includes Safari, Chrome, Firefox)"...?

In my experience, most webdevs do not know what WebKit is.

**Comment by nhoizey** [comment]
I agree, Safari still needs to be mentioned.

Anyway, the column header can still be "Safari on iOS", my issue is more with the title of the pop-in.

**Comment by Fyrd** [comment]
Thanks for bringing this up!

I originally added "& Chrome" when that was the only other major browser that made an iOS shell browser and hadn't updated since others followed. It's also there because developers often ask specifically why Chrome on iOS isn't tracked. I'm a bit worried "& other browsers" is a bit ambiguous but it seems the most appropriate so will switch to that for now.

**Comment by nhoizey** [comment]
Thanks a lot @Fyrd ! 🙏
