### ISSUE TITLE
Revert "nesting is supported"

### ISSUE THREAD

**Issue by romainmenke** [Fyrd/caniuse#6583]
Can we revert this?

There is no reason to mark this as supported.

- no consensus on the specification
- there are critical specification issues that still need to be resolved

_This is adding pressure on the process that isn't helping :)_

_Originally posted by @romainmenke in https://github.com/Fyrd/caniuse/issues/6579#issuecomment-1401958113_

**Comment by Schweinepriester** [comment]
I'm not opposed to reverting per se, but are you able to provide links for those two points?

Because in the [I2S thread for Blink](https://groups.google.com/a/chromium.org/g/blink-dev/c/eFCrkiLynfU/m/JLsh3zQuAAAJ) it sounds quite a bit more optimistic?

> It looks like the CSSWG resolved to adopt "Option 3",
with representatives from all 3 engines voting in favor - and the WebKit
blog survey also resulted in "Option 3" as the top choice.

> I think that we should ship this.

> Taking a look at the open spec issues (https://github.com/w3c/csswg-drafts/labels/css-nesting-1) some are explicitly ideas for future changes, but are there any where shipping amounts to a decision that isn't easily changed? I'm thinking especially of the CSSOM issues.

> Enabled feature for preview (TP?) here:
> 
> https://github.com/WebKit/WebKit/commit/ceafa556d06a475ae4b9362abeb64a42128ce9ee

**Comment by romainmenke** [comment]
This might be the best reference at this time : https://github.com/w3c/csswg-drafts/issues/8249#issuecomment-1399386227

**Comment by Fyrd** [comment]
Alright, has been reverted until it's more certain to be included.

**Comment by Schweinepriester** [comment]
@romainmenke please keep us updated :)

**Comment by romainmenke** [comment]
Thank you all! 🙇
