### ISSUE TITLE
Partial vs full support for `image-set()`

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6669]
Currently all three browser engines have limitations on what `image-set()` can do (which is why it's part of Interop 2023). But some limitations are still marked "full support" while others are marked "partial". 

This doesn't seem consistent. 

https://caniuse.com/css-image-set

<img width="483" alt="Screenshot 2023-04-05 at 12 26 35 PM" src="https://user-images.githubusercontent.com/108474/230144138-65948d89-a53c-455e-b74f-7d12c1fbe2f3.png">

Why is not having support for `calc()` and generated images in `content` considered full support? While not having the type() function or  support while omitting the resolution considered partial?

It seems that every browser with note 2, 3, 4 or 5 should either all be marked full support (with notes), or all be marked partial. 

Thoughts? Does anyone know why Note 3 & 4 = partial while note 2 & 5 = full?

**Comment by atjn** [comment]
Generally speaking, for a feature to be considered fully supported, it must support all common use cases, but does not have to support niche use cases. I would say that the common use cases are:

1:
```css
background-image: image-set("image.png" 1x, "image.png" 2x);
```
2:
```css
background-image: image-set("image.jxl" type("image/jxl"), "image.png" type("image/png"));
```
3:
Combining the two lines above.

Based on that reasoning, I see it this way:

- Note 1: ❌ Partial support - this omits core functionality for at least common use case 2
- Note 2: ✅ Full support - this is only a very niche use case, most people will never encounter it
- Note 3: ❌ Partial support - this omits core functionality for common use case 2
- Note 4: ❌ Partial support - this omits core functionality for common use case 2
- Note 5: ✅ Full support - does not omit core functionality for any common use case, and seems reasonably niche*

*for the last note, I think it is debatable whether it actually is niche. My personal analysis is that the feature will be used somewhat rarely, and if people do use it, they should be reading support notes to check whether their use case is supported.

**Comment by atjn** [comment]
It is worth mentioning that we will probably be demoting all browsers to partial support at some point, because the `image-set` spec is awaiting an expansion that allows for more resolution units, similar to the ones that are available in the `picture` element. This will add another common use case, which no browser suppports right now:
```css
background-image: image-set("image-192w.png" 192w, "image-512w.png" 512w);
```

**Comment by Fyrd** [comment]
I'd started to write a response but @atjn basically covered it. :) If there is a particular use case for using generated images in image-set or for using calc() to set the resolution that may be reason to switch it to partial support. However after a (brief) search I wasn't able to find any blog posts suggesting the use or developers expressing an issue with missing support there. As such the feature is effectively supported but with notes.

On the other hand I did find [this blog post](https://dev.to/jsnkuhn/notes-on-image-set-with-type-55f0) describing the value of using the `(type)` syntax so that one would appear to be more valuable and thus be considered partial support.

**Comment by jensimmons** [comment]
This makes sense. I'm glad to hear folks thought through common use cases vs niche use cases, and there is consistency here. I've closed my PR and will close this issue. Thanks. 

The good news is that because of Interop 2023, it's likely all browsers will get green boxes this year, and web developers will be able to count on `image-set()` to work.
