### ISSUE TITLE
Chromium claims to now support paint-order for HTML text

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#6968]
https://caniuse.com/mdn-css_properties_paint-order
"Does not affect stroked HTML text"

https://issues.chromium.org/issues/41372165
"Support paint-order for HTML text"
"Marked as fixed."

**Comment by 5e-Cleric** [comment]
Additional info:

You can check using this demo: https://codesandbox.io/p/sandbox/eager-resonance-nrd0b?file=%2Fsrc%2Findex.js

![image](https://github.com/mdn/browser-compat-data/assets/91662974/498e6ed4-e68e-4c0c-9328-918cdf2fa8f1)
If the bug is fixed in your chrome version, it will look like the left example.

This is indeed fixed for chrome 123, have not tested 122 personally.

**Comment by Fyrd** [comment]
Indeed the note no longer applies to Chrome 123 so I think this can be closed (this is MDN BCD data btw, not caniuse)
