### ISSUE TITLE
caniuse.com CSS issue(?) making it  ~unuseable

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#7141]
E.g. https://caniuse.com/?search=pushState

![image](https://github.com/user-attachments/assets/a3a9bc3d-bf6a-4afe-93ba-47dbd8a6440e)

Checked Chrome stable, Firefox stable and Chrome on iOS, the latter also on cell.

**Comment by rossjrw** [comment]
Pinging @Fyrd for visibility

**Comment by rjgotten** [comment]
![image](https://github.com/user-attachments/assets/ca6dab77-3c27-45a7-b428-6e5ef2bc87a4)

Smells like someone had a faux-pas with https://sass-lang.com/documentation/breaking-changes/css-vars/

**Comment by streams-in-silence** [comment]
I was able to workaround this issue for now by forcing it to dark mode via the [settings](https://caniuse.com/ciu/settings#theme) instead of default.
![image](https://github.com/user-attachments/assets/f0a9255a-0013-4eab-be09-bbfb1b621935)

But also in dark mode, only the default support table colors work. The color-blind friendly pallet is still broken.
